package com.bizwink.persistence;

import com.bizwink.po.LogColumn;
import com.bizwink.po.LogColumnExample;
import java.math.BigDecimal;

public interface LogColumnMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TLOG_COLUMN
     *
     * @mbggenerated
     */
    int countByExample(LogColumnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TLOG_COLUMN
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(BigDecimal ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TLOG_COLUMN
     *
     * @mbggenerated
     */
    int insert(LogColumn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TLOG_COLUMN
     *
     * @mbggenerated
     */
    int insertSelective(LogColumn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TLOG_COLUMN
     *
     * @mbggenerated
     */
    LogColumn selectByPrimaryKey(BigDecimal ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TLOG_COLUMN
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(LogColumn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TLOG_COLUMN
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LogColumn record);
}