/*
 * JSP generated by Resin-4.0.58 (built Fri, 24 Aug 2018 01:23:14 PDT)
 */

package _jsp._article;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import com.bizwink.cms.util.SessionUtil;
import com.bizwink.cms.security.Auth;
import com.bizwink.cms.markManager.IMarkManager;
import com.bizwink.cms.markManager.markPeer;
import java.util.List;
import com.bizwink.cms.markManager.mark;

public class _recommendarticle__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  private boolean _caucho_isNotModified;
  private com.caucho.jsp.PageManager _jsp_pageManager;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    com.caucho.jsp.PageContextImpl pageContext = _jsp_pageManager.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);

    TagState _jsp_state = null;

    try {
      _jspService(request, response, pageContext, _jsp_application, session, _jsp_state);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_pageManager.freePageContext(pageContext);
    }
  }
  
  private void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response,
              com.caucho.jsp.PageContextImpl pageContext,
              javax.servlet.ServletContext application,
              javax.servlet.http.HttpSession session,
              TagState _jsp_state)
    throws Throwable
  {
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.jsp.tagext.JspTag _jsp_parent_tag = null;
    com.caucho.jsp.PageContextImpl _jsp_parentContext = pageContext;
    response.setContentType("text/html;charset=utf-8");

    out.write(_jsp_string0, 0, _jsp_string0.length);
    
    Auth authToken = SessionUtil.getUserAuthorization(request, response, session);
    if (authToken == null) {
        response.sendRedirect(response.encodeRedirectURL("/webbuilder/index.jsp?msg=\u7cfb\u7edf\u8d85\u65f6\uff0c\u8bf7\u91cd\u65b0\u767b\u9646!"));
        return;
    }

    int siteid = authToken.getSiteID();

    IMarkManager markManager = markPeer.getInstance();
    //\u83b7\u53d6\u63a8\u8350\u6587\u7ae0\u5217\u8868\u6807\u8bb0
    List marks = markManager.getMarksByType(siteid,12);
    mark mark = null;

    out.write(_jsp_string1, 0, _jsp_string1.length);
    
    for(int ii=0; ii<marks.size(); ii++) {
        mark = (mark)marks.get(ii);

    out.write(_jsp_string2, 0, _jsp_string2.length);
    out.print((mark.getID()));
    out.write(_jsp_string3, 0, _jsp_string3.length);
    out.print((mark.getChineseName()));
    out.write(_jsp_string4, 0, _jsp_string4.length);
    }
    out.write(_jsp_string5, 0, _jsp_string5.length);
    out.print((marks.size()));
    out.write(_jsp_string6, 0, _jsp_string6.length);
  }

  private com.caucho.make.DependencyContainer _caucho_depends
    = new com.caucho.make.DependencyContainer();

  public java.util.ArrayList<com.caucho.vfs.Dependency> _caucho_getDependList()
  {
    return _caucho_depends.getDependencies();
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    _caucho_depends.add(depend);
  }

  protected void _caucho_setNeverModified(boolean isNotModified)
  {
    _caucho_isNotModified = true;
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;

    if (_caucho_isNotModified)
      return false;

    if (com.caucho.server.util.CauchoSystem.getVersionId() != 6165118203484593848L)
      return true;

    return _caucho_depends.isModified();
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
    TagState tagState;
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("article/recommendArticle.jsp"), -2312644698580968872L, false);
    _caucho_depends.add(depend);
    loader.addDependency(depend);
  }

  final static class TagState {

    void release()
    {
    }
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void caucho_init(ServletConfig config)
  {
    try {
      com.caucho.server.webapp.WebApp webApp
        = (com.caucho.server.webapp.WebApp) config.getServletContext();
      init(config);
      if (com.caucho.jsp.JspManager.getCheckInterval() >= 0)
        _caucho_depends.setCheckInterval(com.caucho.jsp.JspManager.getCheckInterval());
      _jsp_pageManager = webApp.getJspApplicationContext().getPageManager();
      com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
      com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.InitPageContextImpl(webApp, this);
    } catch (Exception e) {
      throw com.caucho.config.ConfigException.create(e);
    }
  }

  private final static char []_jsp_string3;
  private final static char []_jsp_string2;
  private final static char []_jsp_string6;
  private final static char []_jsp_string0;
  private final static char []_jsp_string1;
  private final static char []_jsp_string5;
  private final static char []_jsp_string4;
  static {
    _jsp_string3 = "\">".toCharArray();
    _jsp_string2 = "\r\n<input type=\"checkbox\" name=\"recommend\" id=\"recommendID\" value=\"".toCharArray();
    _jsp_string6 = ";\r\n        var recommend_select = window.opener.document.createForm.recommendID;\r\n        //var recommend_select = $(\"#recommendID\", window.opener.document.createForm);\r\n        var r=document.getElementsByName(\"recommend\");\r\n        for (var i = 0; i < recommend_select.length; i++) {\r\n            var valueAndText = recommend_select.options[i].value;         // \u9009\u4e2d\u503c\r\n            var posi = valueAndText.indexOf(\"-\");\r\n            var value = valueAndText.substring(0,posi);\r\n            value = value.substring(1);\r\n            for (var j=0; j<check_item_size; j++) {\r\n                if (r[j].value == value){\r\n                    r[j].checked=true;\r\n                    break;\r\n                }\r\n            }\r\n        }\r\n    });\r\n\r\n    $(\"#save\").click(function(){\r\n        var recommend_select = $(\"#recommendID\", window.opener.document);\r\n        recommend_select.empty();\r\n        var r=document.getElementsByName(\"recommend\");\r\n        for(var i=0;i<r.length;i++){\r\n            if(r[i].checked){\r\n                recommend_select.append(\"<option value='a\" + r[i].value + \"-\" + r[i].nextSibling.nodeValue + \"'>\" + r[i].nextSibling.nodeValue + \"</option>\");\r\n                window.close();\r\n            }\r\n        }\r\n    });\r\n\r\n    $(\"#close\").click(function(){\r\n        window.close();\r\n    });\r\n</script>\r\n</html>\r\n".toCharArray();
    _jsp_string0 = "\r\n\r\n\r\n\r\n\r\n\r\n\r\n".toCharArray();
    _jsp_string1 = "\r\n<html>\r\n<head>\r\n    <title>\u63a8\u8350\u6587\u7ae0</title>\r\n    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n    <script type=\"text/javascript\" src=\"../js/jquery-1.12.4.js\"></script>\r\n</head>\r\n<body>\r\n".toCharArray();
    _jsp_string5 = "\r\n<br/><br/>\r\n<input type=\"button\" name=\"tijiao\" value=\"\u4fdd\u5b58\" id=\"save\">\r\n<input type=\"button\" name=\"cancel\" value=\"\u8fd4\u56de\" id=\"close\">\r\n</body>\r\n<script language=javascript>\r\n    $(document).ready(function() {\r\n        var check_item_size = ".toCharArray();
    _jsp_string4 = "\r\n".toCharArray();
  }
}
