/*
 * JSP generated by Resin-4.0.58 (built Fri, 24 Aug 2018 01:23:14 PDT)
 */

package _jsp._article;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.sql.*;
import java.util.*;
import com.bizwink.cms.news.*;
import com.bizwink.cms.modelManager.*;
import com.bizwink.cms.security.*;
import com.bizwink.cms.util.*;

public class _selectmodelright__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  private boolean _caucho_isNotModified;
  private com.caucho.jsp.PageManager _jsp_pageManager;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    com.caucho.jsp.PageContextImpl pageContext = _jsp_pageManager.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);

    TagState _jsp_state = null;

    try {
      _jspService(request, response, pageContext, _jsp_application, session, _jsp_state);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_pageManager.freePageContext(pageContext);
    }
  }
  
  private void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response,
              com.caucho.jsp.PageContextImpl pageContext,
              javax.servlet.ServletContext application,
              javax.servlet.http.HttpSession session,
              TagState _jsp_state)
    throws Throwable
  {
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.jsp.tagext.JspTag _jsp_parent_tag = null;
    com.caucho.jsp.PageContextImpl _jsp_parentContext = pageContext;
    response.setContentType("text/html;charset=utf-8");

    out.write(_jsp_string0, 0, _jsp_string0.length);
    
  Auth authToken = SessionUtil.getUserAuthorization(request,response,session);
  if (authToken == null)
  {
    response.sendRedirect(response.encodeRedirectURL("../login.jsp?msg=\u7cfb\u7edf\u8d85\u65f6\uff0c\u8bf7\u91cd\u65b0\u767b\u9646!"));
    return;
  }

  int columnID = ParamUtil.getIntParameter(request, "column", 0);

  IModelManager modelManager = ModelPeer.getInstance();
  IColumnManager columnManager = ColumnPeer.getInstance();
  Column column = columnManager.getColumn(columnID);
  String cname = StringUtil.gb2iso4View(column.getCName());

  List templateList = modelManager.getArticleModels(columnID);

    out.write(_jsp_string1, 0, _jsp_string1.length);
    out.print((columnID));
    out.write(_jsp_string2, 0, _jsp_string2.length);
    out.print((cname));
    out.write(_jsp_string3, 0, _jsp_string3.length);
    
  for (int i=0; i<templateList.size(); i++)
  {
    Model template = (Model)templateList.get(i);

    int templateID = template.getID();
    String editor = template.getEditor();
    String lastupdated = template.getLastupdated().toString().substring(0,10);
    String templateName = template.getChineseName();
    if (templateName == null) templateName = "";
    templateName = StringUtil.gb2iso4View(templateName);

    String bgcolor = (i%2==0) ? "#EEC000" : "#FFCC00";
    out.println("<tr bgcolor=" + bgcolor + " height=22>");
    out.println("<td>&nbsp;" + templateName + "</td>");
    out.println("<td>&nbsp;" + template.getTemplateName() + "</td>");
    out.println("<td align=center>\u6587\u7ae0\u6a21\u677f</td>");
    out.println("<td align=center>" + lastupdated + "</td>");
    out.println("<td>&nbsp;" + editor + "</td>");
    if (template.getDefaultTemplate() == 1)
      out.println("<td align=center><img src='../images/tasklist.gif' align=bottom border=0></td>");
    else
      out.println("<td align=center>&nbsp;</td>");
    out.println("<td align=center><a href=javascript:Preview("+templateID+","+template.getIsArticle()+");><img src=../images/preview.gif border=0></a></td>");
    out.println("<td align=center><a href=javascript:SelectModel("+templateID+");><img src=../images/edit.gif border=0></a></td></tr>");
  }

    out.write(_jsp_string4, 0, _jsp_string4.length);
  }

  private com.caucho.make.DependencyContainer _caucho_depends
    = new com.caucho.make.DependencyContainer();

  public java.util.ArrayList<com.caucho.vfs.Dependency> _caucho_getDependList()
  {
    return _caucho_depends.getDependencies();
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    _caucho_depends.add(depend);
  }

  protected void _caucho_setNeverModified(boolean isNotModified)
  {
    _caucho_isNotModified = true;
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;

    if (_caucho_isNotModified)
      return false;

    if (com.caucho.server.util.CauchoSystem.getVersionId() != 6165118203484593848L)
      return true;

    return _caucho_depends.isModified();
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
    TagState tagState;
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("article/selectModelRight.jsp"), -5649018516217709824L, false);
    _caucho_depends.add(depend);
    loader.addDependency(depend);
  }

  final static class TagState {

    void release()
    {
    }
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void caucho_init(ServletConfig config)
  {
    try {
      com.caucho.server.webapp.WebApp webApp
        = (com.caucho.server.webapp.WebApp) config.getServletContext();
      init(config);
      if (com.caucho.jsp.JspManager.getCheckInterval() >= 0)
        _caucho_depends.setCheckInterval(com.caucho.jsp.JspManager.getCheckInterval());
      _jsp_pageManager = webApp.getJspApplicationContext().getPageManager();
      com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
      com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.InitPageContextImpl(webApp, this);
    } catch (Exception e) {
      throw com.caucho.config.ConfigException.create(e);
    }
  }

  private final static char []_jsp_string3;
  private final static char []_jsp_string4;
  private final static char []_jsp_string2;
  private final static char []_jsp_string0;
  private final static char []_jsp_string1;
  static {
    _jsp_string3 = "</td></tr>\r\n<tr bgcolor=#dddddd class=tine>\r\n<td align=center width='20%'>\u4e2d\u6587\u540d\u79f0</td>\r\n<td align=center width='14%'>\u82f1\u6587\u540d\u79f0</td>\r\n<td align=center width='14%'>\u6a21\u677f\u7c7b\u578b</td>\r\n<td align=center width='14%'>\u4fee\u6539\u65f6\u95f4</td>\r\n<td align=center width='14%'>\u7f16\u8f91</td>\r\n<td align=center width='8%'>\u9ed8\u8ba4</td>\r\n<td align=center width='8%'>\u9884\u89c8</td>\r\n<td align=center width='8%'>\u9009\u62e9</td>\r\n</tr>\r\n".toCharArray();
    _jsp_string4 = "\r\n</table>\r\n</center>\r\n</BODY>\r\n</html>\r\n".toCharArray();
    _jsp_string2 = "&template=\"+templateID+\"&isArticle=\"+isArticle,\"PreviewTemplate\",\"width=800,height=600,left=0,top=0,scrollbars\");\r\n}\r\n\r\nfunction SelectModel(modelID)\r\n{\r\n    var isMSIE = (navigator.appName == \"Microsoft Internet Explorer\");\r\n    if (isMSIE) {\r\n        window.returnValue = modelID;\r\n        window.close();\r\n    }else{\r\n        window.parent.opener.document.getElementById(\"modelID\").value = modelID;\r\n        top.close();\r\n    }\r\n}\r\n</script>\r\n</head>\r\n\r\n<BODY BGCOLOR=#ffffff LINK=#000099 ALINK=#cc0000 VLINK=#000099 TOMARGIN=8>\r\n<center>\r\n<table border=1 borderColorDark=#ffffec borderColorLight=#5e5e00 cellPadding=0 cellSpacing=0 width='100%'>\r\n<tr class=tine><td colspan=8>\u5f53\u524d\u680f\u76ee\uff1a".toCharArray();
    _jsp_string0 = "\r\n".toCharArray();
    _jsp_string1 = "\r\n\r\n<html>\r\n<head>\r\n<title></title>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n<link rel=stylesheet type=text/css href=\"../style/global.css\">\r\n<script language=\"javascript\">\r\nfunction Preview(templateID, isArticle)\r\n{\r\n  window.open(\"previewTemplate.jsp?column=".toCharArray();
  }
}
