package com.bizwink.po;

import java.math.BigDecimal;

public class LogColumn {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TLOG_COLUMN.ID
     *
     * @mbggenerated
     */
    private BigDecimal ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TLOG_COLUMN.DOMAINID
     *
     * @mbggenerated
     */
    private BigDecimal DOMAINID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TLOG_COLUMN.HOSTID
     *
     * @mbggenerated
     */
    private BigDecimal HOSTID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TLOG_COLUMN.COLID
     *
     * @mbggenerated
     */
    private BigDecimal COLID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TLOG_COLUMN.PCOLID
     *
     * @mbggenerated
     */
    private BigDecimal PCOLID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TLOG_COLUMN.COLNAME
     *
     * @mbggenerated
     */
    private String COLNAME;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TLOG_COLUMN.COLDIR
     *
     * @mbggenerated
     */
    private String COLDIR;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TLOG_COLUMN.ID
     *
     * @return the value of TLOG_COLUMN.ID
     *
     * @mbggenerated
     */
    public BigDecimal getID() {
        return ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TLOG_COLUMN.ID
     *
     * @param ID the value for TLOG_COLUMN.ID
     *
     * @mbggenerated
     */
    public void setID(BigDecimal ID) {
        this.ID = ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TLOG_COLUMN.DOMAINID
     *
     * @return the value of TLOG_COLUMN.DOMAINID
     *
     * @mbggenerated
     */
    public BigDecimal getDOMAINID() {
        return DOMAINID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TLOG_COLUMN.DOMAINID
     *
     * @param DOMAINID the value for TLOG_COLUMN.DOMAINID
     *
     * @mbggenerated
     */
    public void setDOMAINID(BigDecimal DOMAINID) {
        this.DOMAINID = DOMAINID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TLOG_COLUMN.HOSTID
     *
     * @return the value of TLOG_COLUMN.HOSTID
     *
     * @mbggenerated
     */
    public BigDecimal getHOSTID() {
        return HOSTID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TLOG_COLUMN.HOSTID
     *
     * @param HOSTID the value for TLOG_COLUMN.HOSTID
     *
     * @mbggenerated
     */
    public void setHOSTID(BigDecimal HOSTID) {
        this.HOSTID = HOSTID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TLOG_COLUMN.COLID
     *
     * @return the value of TLOG_COLUMN.COLID
     *
     * @mbggenerated
     */
    public BigDecimal getCOLID() {
        return COLID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TLOG_COLUMN.COLID
     *
     * @param COLID the value for TLOG_COLUMN.COLID
     *
     * @mbggenerated
     */
    public void setCOLID(BigDecimal COLID) {
        this.COLID = COLID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TLOG_COLUMN.PCOLID
     *
     * @return the value of TLOG_COLUMN.PCOLID
     *
     * @mbggenerated
     */
    public BigDecimal getPCOLID() {
        return PCOLID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TLOG_COLUMN.PCOLID
     *
     * @param PCOLID the value for TLOG_COLUMN.PCOLID
     *
     * @mbggenerated
     */
    public void setPCOLID(BigDecimal PCOLID) {
        this.PCOLID = PCOLID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TLOG_COLUMN.COLNAME
     *
     * @return the value of TLOG_COLUMN.COLNAME
     *
     * @mbggenerated
     */
    public String getCOLNAME() {
        return COLNAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TLOG_COLUMN.COLNAME
     *
     * @param COLNAME the value for TLOG_COLUMN.COLNAME
     *
     * @mbggenerated
     */
    public void setCOLNAME(String COLNAME) {
        this.COLNAME = COLNAME == null ? null : COLNAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TLOG_COLUMN.COLDIR
     *
     * @return the value of TLOG_COLUMN.COLDIR
     *
     * @mbggenerated
     */
    public String getCOLDIR() {
        return COLDIR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TLOG_COLUMN.COLDIR
     *
     * @param COLDIR the value for TLOG_COLUMN.COLDIR
     *
     * @mbggenerated
     */
    public void setCOLDIR(String COLDIR) {
        this.COLDIR = COLDIR == null ? null : COLDIR.trim();
    }
}