package com.bizwink.po;

import java.math.BigDecimal;

public class LogDomaininfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TLOG_DOMAININFO.ID
     *
     * @mbggenerated
     */
    private BigDecimal ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TLOG_DOMAININFO.DOMAINNAME
     *
     * @mbggenerated
     */
    private String DOMAINNAME;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TLOG_DOMAININFO.ID
     *
     * @return the value of TLOG_DOMAININFO.ID
     *
     * @mbggenerated
     */
    public BigDecimal getID() {
        return ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TLOG_DOMAININFO.ID
     *
     * @param ID the value for TLOG_DOMAININFO.ID
     *
     * @mbggenerated
     */
    public void setID(BigDecimal ID) {
        this.ID = ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TLOG_DOMAININFO.DOMAINNAME
     *
     * @return the value of TLOG_DOMAININFO.DOMAINNAME
     *
     * @mbggenerated
     */
    public String getDOMAINNAME() {
        return DOMAINNAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TLOG_DOMAININFO.DOMAINNAME
     *
     * @param DOMAINNAME the value for TLOG_DOMAININFO.DOMAINNAME
     *
     * @mbggenerated
     */
    public void setDOMAINNAME(String DOMAINNAME) {
        this.DOMAINNAME = DOMAINNAME == null ? null : DOMAINNAME.trim();
    }
}