package com.bizwink.po;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class LogHostinfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TLOG_HOSTINFO
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TLOG_HOSTINFO
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TLOG_HOSTINFO
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TLOG_HOSTINFO
     *
     * @mbggenerated
     */
    public LogHostinfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TLOG_HOSTINFO
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TLOG_HOSTINFO
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TLOG_HOSTINFO
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TLOG_HOSTINFO
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TLOG_HOSTINFO
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TLOG_HOSTINFO
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TLOG_HOSTINFO
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TLOG_HOSTINFO
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TLOG_HOSTINFO
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TLOG_HOSTINFO
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TLOG_HOSTINFO
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIDIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIDIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIDEqualTo(BigDecimal value) {
            addCriterion("ID =", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDNotEqualTo(BigDecimal value) {
            addCriterion("ID <>", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDGreaterThan(BigDecimal value) {
            addCriterion("ID >", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ID >=", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDLessThan(BigDecimal value) {
            addCriterion("ID <", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ID <=", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDIn(List<BigDecimal> values) {
            addCriterion("ID in", values, "ID");
            return (Criteria) this;
        }

        public Criteria andIDNotIn(List<BigDecimal> values) {
            addCriterion("ID not in", values, "ID");
            return (Criteria) this;
        }

        public Criteria andIDBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ID between", value1, value2, "ID");
            return (Criteria) this;
        }

        public Criteria andIDNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ID not between", value1, value2, "ID");
            return (Criteria) this;
        }

        public Criteria andDOMAINIDIsNull() {
            addCriterion("DOMAINID is null");
            return (Criteria) this;
        }

        public Criteria andDOMAINIDIsNotNull() {
            addCriterion("DOMAINID is not null");
            return (Criteria) this;
        }

        public Criteria andDOMAINIDEqualTo(BigDecimal value) {
            addCriterion("DOMAINID =", value, "DOMAINID");
            return (Criteria) this;
        }

        public Criteria andDOMAINIDNotEqualTo(BigDecimal value) {
            addCriterion("DOMAINID <>", value, "DOMAINID");
            return (Criteria) this;
        }

        public Criteria andDOMAINIDGreaterThan(BigDecimal value) {
            addCriterion("DOMAINID >", value, "DOMAINID");
            return (Criteria) this;
        }

        public Criteria andDOMAINIDGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("DOMAINID >=", value, "DOMAINID");
            return (Criteria) this;
        }

        public Criteria andDOMAINIDLessThan(BigDecimal value) {
            addCriterion("DOMAINID <", value, "DOMAINID");
            return (Criteria) this;
        }

        public Criteria andDOMAINIDLessThanOrEqualTo(BigDecimal value) {
            addCriterion("DOMAINID <=", value, "DOMAINID");
            return (Criteria) this;
        }

        public Criteria andDOMAINIDIn(List<BigDecimal> values) {
            addCriterion("DOMAINID in", values, "DOMAINID");
            return (Criteria) this;
        }

        public Criteria andDOMAINIDNotIn(List<BigDecimal> values) {
            addCriterion("DOMAINID not in", values, "DOMAINID");
            return (Criteria) this;
        }

        public Criteria andDOMAINIDBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("DOMAINID between", value1, value2, "DOMAINID");
            return (Criteria) this;
        }

        public Criteria andDOMAINIDNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("DOMAINID not between", value1, value2, "DOMAINID");
            return (Criteria) this;
        }

        public Criteria andHOSTNAMEIsNull() {
            addCriterion("HOSTNAME is null");
            return (Criteria) this;
        }

        public Criteria andHOSTNAMEIsNotNull() {
            addCriterion("HOSTNAME is not null");
            return (Criteria) this;
        }

        public Criteria andHOSTNAMEEqualTo(String value) {
            addCriterion("HOSTNAME =", value, "HOSTNAME");
            return (Criteria) this;
        }

        public Criteria andHOSTNAMENotEqualTo(String value) {
            addCriterion("HOSTNAME <>", value, "HOSTNAME");
            return (Criteria) this;
        }

        public Criteria andHOSTNAMEGreaterThan(String value) {
            addCriterion("HOSTNAME >", value, "HOSTNAME");
            return (Criteria) this;
        }

        public Criteria andHOSTNAMEGreaterThanOrEqualTo(String value) {
            addCriterion("HOSTNAME >=", value, "HOSTNAME");
            return (Criteria) this;
        }

        public Criteria andHOSTNAMELessThan(String value) {
            addCriterion("HOSTNAME <", value, "HOSTNAME");
            return (Criteria) this;
        }

        public Criteria andHOSTNAMELessThanOrEqualTo(String value) {
            addCriterion("HOSTNAME <=", value, "HOSTNAME");
            return (Criteria) this;
        }

        public Criteria andHOSTNAMELike(String value) {
            addCriterion("HOSTNAME like", value, "HOSTNAME");
            return (Criteria) this;
        }

        public Criteria andHOSTNAMENotLike(String value) {
            addCriterion("HOSTNAME not like", value, "HOSTNAME");
            return (Criteria) this;
        }

        public Criteria andHOSTNAMEIn(List<String> values) {
            addCriterion("HOSTNAME in", values, "HOSTNAME");
            return (Criteria) this;
        }

        public Criteria andHOSTNAMENotIn(List<String> values) {
            addCriterion("HOSTNAME not in", values, "HOSTNAME");
            return (Criteria) this;
        }

        public Criteria andHOSTNAMEBetween(String value1, String value2) {
            addCriterion("HOSTNAME between", value1, value2, "HOSTNAME");
            return (Criteria) this;
        }

        public Criteria andHOSTNAMENotBetween(String value1, String value2) {
            addCriterion("HOSTNAME not between", value1, value2, "HOSTNAME");
            return (Criteria) this;
        }

        public Criteria andIPADDRESSIsNull() {
            addCriterion("IPADDRESS is null");
            return (Criteria) this;
        }

        public Criteria andIPADDRESSIsNotNull() {
            addCriterion("IPADDRESS is not null");
            return (Criteria) this;
        }

        public Criteria andIPADDRESSEqualTo(String value) {
            addCriterion("IPADDRESS =", value, "IPADDRESS");
            return (Criteria) this;
        }

        public Criteria andIPADDRESSNotEqualTo(String value) {
            addCriterion("IPADDRESS <>", value, "IPADDRESS");
            return (Criteria) this;
        }

        public Criteria andIPADDRESSGreaterThan(String value) {
            addCriterion("IPADDRESS >", value, "IPADDRESS");
            return (Criteria) this;
        }

        public Criteria andIPADDRESSGreaterThanOrEqualTo(String value) {
            addCriterion("IPADDRESS >=", value, "IPADDRESS");
            return (Criteria) this;
        }

        public Criteria andIPADDRESSLessThan(String value) {
            addCriterion("IPADDRESS <", value, "IPADDRESS");
            return (Criteria) this;
        }

        public Criteria andIPADDRESSLessThanOrEqualTo(String value) {
            addCriterion("IPADDRESS <=", value, "IPADDRESS");
            return (Criteria) this;
        }

        public Criteria andIPADDRESSLike(String value) {
            addCriterion("IPADDRESS like", value, "IPADDRESS");
            return (Criteria) this;
        }

        public Criteria andIPADDRESSNotLike(String value) {
            addCriterion("IPADDRESS not like", value, "IPADDRESS");
            return (Criteria) this;
        }

        public Criteria andIPADDRESSIn(List<String> values) {
            addCriterion("IPADDRESS in", values, "IPADDRESS");
            return (Criteria) this;
        }

        public Criteria andIPADDRESSNotIn(List<String> values) {
            addCriterion("IPADDRESS not in", values, "IPADDRESS");
            return (Criteria) this;
        }

        public Criteria andIPADDRESSBetween(String value1, String value2) {
            addCriterion("IPADDRESS between", value1, value2, "IPADDRESS");
            return (Criteria) this;
        }

        public Criteria andIPADDRESSNotBetween(String value1, String value2) {
            addCriterion("IPADDRESS not between", value1, value2, "IPADDRESS");
            return (Criteria) this;
        }

        public Criteria andFTPUSERNAMEIsNull() {
            addCriterion("FTPUSERNAME is null");
            return (Criteria) this;
        }

        public Criteria andFTPUSERNAMEIsNotNull() {
            addCriterion("FTPUSERNAME is not null");
            return (Criteria) this;
        }

        public Criteria andFTPUSERNAMEEqualTo(String value) {
            addCriterion("FTPUSERNAME =", value, "FTPUSERNAME");
            return (Criteria) this;
        }

        public Criteria andFTPUSERNAMENotEqualTo(String value) {
            addCriterion("FTPUSERNAME <>", value, "FTPUSERNAME");
            return (Criteria) this;
        }

        public Criteria andFTPUSERNAMEGreaterThan(String value) {
            addCriterion("FTPUSERNAME >", value, "FTPUSERNAME");
            return (Criteria) this;
        }

        public Criteria andFTPUSERNAMEGreaterThanOrEqualTo(String value) {
            addCriterion("FTPUSERNAME >=", value, "FTPUSERNAME");
            return (Criteria) this;
        }

        public Criteria andFTPUSERNAMELessThan(String value) {
            addCriterion("FTPUSERNAME <", value, "FTPUSERNAME");
            return (Criteria) this;
        }

        public Criteria andFTPUSERNAMELessThanOrEqualTo(String value) {
            addCriterion("FTPUSERNAME <=", value, "FTPUSERNAME");
            return (Criteria) this;
        }

        public Criteria andFTPUSERNAMELike(String value) {
            addCriterion("FTPUSERNAME like", value, "FTPUSERNAME");
            return (Criteria) this;
        }

        public Criteria andFTPUSERNAMENotLike(String value) {
            addCriterion("FTPUSERNAME not like", value, "FTPUSERNAME");
            return (Criteria) this;
        }

        public Criteria andFTPUSERNAMEIn(List<String> values) {
            addCriterion("FTPUSERNAME in", values, "FTPUSERNAME");
            return (Criteria) this;
        }

        public Criteria andFTPUSERNAMENotIn(List<String> values) {
            addCriterion("FTPUSERNAME not in", values, "FTPUSERNAME");
            return (Criteria) this;
        }

        public Criteria andFTPUSERNAMEBetween(String value1, String value2) {
            addCriterion("FTPUSERNAME between", value1, value2, "FTPUSERNAME");
            return (Criteria) this;
        }

        public Criteria andFTPUSERNAMENotBetween(String value1, String value2) {
            addCriterion("FTPUSERNAME not between", value1, value2, "FTPUSERNAME");
            return (Criteria) this;
        }

        public Criteria andFTPPASSWORDIsNull() {
            addCriterion("FTPPASSWORD is null");
            return (Criteria) this;
        }

        public Criteria andFTPPASSWORDIsNotNull() {
            addCriterion("FTPPASSWORD is not null");
            return (Criteria) this;
        }

        public Criteria andFTPPASSWORDEqualTo(String value) {
            addCriterion("FTPPASSWORD =", value, "FTPPASSWORD");
            return (Criteria) this;
        }

        public Criteria andFTPPASSWORDNotEqualTo(String value) {
            addCriterion("FTPPASSWORD <>", value, "FTPPASSWORD");
            return (Criteria) this;
        }

        public Criteria andFTPPASSWORDGreaterThan(String value) {
            addCriterion("FTPPASSWORD >", value, "FTPPASSWORD");
            return (Criteria) this;
        }

        public Criteria andFTPPASSWORDGreaterThanOrEqualTo(String value) {
            addCriterion("FTPPASSWORD >=", value, "FTPPASSWORD");
            return (Criteria) this;
        }

        public Criteria andFTPPASSWORDLessThan(String value) {
            addCriterion("FTPPASSWORD <", value, "FTPPASSWORD");
            return (Criteria) this;
        }

        public Criteria andFTPPASSWORDLessThanOrEqualTo(String value) {
            addCriterion("FTPPASSWORD <=", value, "FTPPASSWORD");
            return (Criteria) this;
        }

        public Criteria andFTPPASSWORDLike(String value) {
            addCriterion("FTPPASSWORD like", value, "FTPPASSWORD");
            return (Criteria) this;
        }

        public Criteria andFTPPASSWORDNotLike(String value) {
            addCriterion("FTPPASSWORD not like", value, "FTPPASSWORD");
            return (Criteria) this;
        }

        public Criteria andFTPPASSWORDIn(List<String> values) {
            addCriterion("FTPPASSWORD in", values, "FTPPASSWORD");
            return (Criteria) this;
        }

        public Criteria andFTPPASSWORDNotIn(List<String> values) {
            addCriterion("FTPPASSWORD not in", values, "FTPPASSWORD");
            return (Criteria) this;
        }

        public Criteria andFTPPASSWORDBetween(String value1, String value2) {
            addCriterion("FTPPASSWORD between", value1, value2, "FTPPASSWORD");
            return (Criteria) this;
        }

        public Criteria andFTPPASSWORDNotBetween(String value1, String value2) {
            addCriterion("FTPPASSWORD not between", value1, value2, "FTPPASSWORD");
            return (Criteria) this;
        }

        public Criteria andORGLOGPATHIsNull() {
            addCriterion("ORGLOGPATH is null");
            return (Criteria) this;
        }

        public Criteria andORGLOGPATHIsNotNull() {
            addCriterion("ORGLOGPATH is not null");
            return (Criteria) this;
        }

        public Criteria andORGLOGPATHEqualTo(String value) {
            addCriterion("ORGLOGPATH =", value, "ORGLOGPATH");
            return (Criteria) this;
        }

        public Criteria andORGLOGPATHNotEqualTo(String value) {
            addCriterion("ORGLOGPATH <>", value, "ORGLOGPATH");
            return (Criteria) this;
        }

        public Criteria andORGLOGPATHGreaterThan(String value) {
            addCriterion("ORGLOGPATH >", value, "ORGLOGPATH");
            return (Criteria) this;
        }

        public Criteria andORGLOGPATHGreaterThanOrEqualTo(String value) {
            addCriterion("ORGLOGPATH >=", value, "ORGLOGPATH");
            return (Criteria) this;
        }

        public Criteria andORGLOGPATHLessThan(String value) {
            addCriterion("ORGLOGPATH <", value, "ORGLOGPATH");
            return (Criteria) this;
        }

        public Criteria andORGLOGPATHLessThanOrEqualTo(String value) {
            addCriterion("ORGLOGPATH <=", value, "ORGLOGPATH");
            return (Criteria) this;
        }

        public Criteria andORGLOGPATHLike(String value) {
            addCriterion("ORGLOGPATH like", value, "ORGLOGPATH");
            return (Criteria) this;
        }

        public Criteria andORGLOGPATHNotLike(String value) {
            addCriterion("ORGLOGPATH not like", value, "ORGLOGPATH");
            return (Criteria) this;
        }

        public Criteria andORGLOGPATHIn(List<String> values) {
            addCriterion("ORGLOGPATH in", values, "ORGLOGPATH");
            return (Criteria) this;
        }

        public Criteria andORGLOGPATHNotIn(List<String> values) {
            addCriterion("ORGLOGPATH not in", values, "ORGLOGPATH");
            return (Criteria) this;
        }

        public Criteria andORGLOGPATHBetween(String value1, String value2) {
            addCriterion("ORGLOGPATH between", value1, value2, "ORGLOGPATH");
            return (Criteria) this;
        }

        public Criteria andORGLOGPATHNotBetween(String value1, String value2) {
            addCriterion("ORGLOGPATH not between", value1, value2, "ORGLOGPATH");
            return (Criteria) this;
        }

        public Criteria andLOGTYPEIsNull() {
            addCriterion("LOGTYPE is null");
            return (Criteria) this;
        }

        public Criteria andLOGTYPEIsNotNull() {
            addCriterion("LOGTYPE is not null");
            return (Criteria) this;
        }

        public Criteria andLOGTYPEEqualTo(String value) {
            addCriterion("LOGTYPE =", value, "LOGTYPE");
            return (Criteria) this;
        }

        public Criteria andLOGTYPENotEqualTo(String value) {
            addCriterion("LOGTYPE <>", value, "LOGTYPE");
            return (Criteria) this;
        }

        public Criteria andLOGTYPEGreaterThan(String value) {
            addCriterion("LOGTYPE >", value, "LOGTYPE");
            return (Criteria) this;
        }

        public Criteria andLOGTYPEGreaterThanOrEqualTo(String value) {
            addCriterion("LOGTYPE >=", value, "LOGTYPE");
            return (Criteria) this;
        }

        public Criteria andLOGTYPELessThan(String value) {
            addCriterion("LOGTYPE <", value, "LOGTYPE");
            return (Criteria) this;
        }

        public Criteria andLOGTYPELessThanOrEqualTo(String value) {
            addCriterion("LOGTYPE <=", value, "LOGTYPE");
            return (Criteria) this;
        }

        public Criteria andLOGTYPELike(String value) {
            addCriterion("LOGTYPE like", value, "LOGTYPE");
            return (Criteria) this;
        }

        public Criteria andLOGTYPENotLike(String value) {
            addCriterion("LOGTYPE not like", value, "LOGTYPE");
            return (Criteria) this;
        }

        public Criteria andLOGTYPEIn(List<String> values) {
            addCriterion("LOGTYPE in", values, "LOGTYPE");
            return (Criteria) this;
        }

        public Criteria andLOGTYPENotIn(List<String> values) {
            addCriterion("LOGTYPE not in", values, "LOGTYPE");
            return (Criteria) this;
        }

        public Criteria andLOGTYPEBetween(String value1, String value2) {
            addCriterion("LOGTYPE between", value1, value2, "LOGTYPE");
            return (Criteria) this;
        }

        public Criteria andLOGTYPENotBetween(String value1, String value2) {
            addCriterion("LOGTYPE not between", value1, value2, "LOGTYPE");
            return (Criteria) this;
        }

        public Criteria andREJTYPEIsNull() {
            addCriterion("REJTYPE is null");
            return (Criteria) this;
        }

        public Criteria andREJTYPEIsNotNull() {
            addCriterion("REJTYPE is not null");
            return (Criteria) this;
        }

        public Criteria andREJTYPEEqualTo(String value) {
            addCriterion("REJTYPE =", value, "REJTYPE");
            return (Criteria) this;
        }

        public Criteria andREJTYPENotEqualTo(String value) {
            addCriterion("REJTYPE <>", value, "REJTYPE");
            return (Criteria) this;
        }

        public Criteria andREJTYPEGreaterThan(String value) {
            addCriterion("REJTYPE >", value, "REJTYPE");
            return (Criteria) this;
        }

        public Criteria andREJTYPEGreaterThanOrEqualTo(String value) {
            addCriterion("REJTYPE >=", value, "REJTYPE");
            return (Criteria) this;
        }

        public Criteria andREJTYPELessThan(String value) {
            addCriterion("REJTYPE <", value, "REJTYPE");
            return (Criteria) this;
        }

        public Criteria andREJTYPELessThanOrEqualTo(String value) {
            addCriterion("REJTYPE <=", value, "REJTYPE");
            return (Criteria) this;
        }

        public Criteria andREJTYPELike(String value) {
            addCriterion("REJTYPE like", value, "REJTYPE");
            return (Criteria) this;
        }

        public Criteria andREJTYPENotLike(String value) {
            addCriterion("REJTYPE not like", value, "REJTYPE");
            return (Criteria) this;
        }

        public Criteria andREJTYPEIn(List<String> values) {
            addCriterion("REJTYPE in", values, "REJTYPE");
            return (Criteria) this;
        }

        public Criteria andREJTYPENotIn(List<String> values) {
            addCriterion("REJTYPE not in", values, "REJTYPE");
            return (Criteria) this;
        }

        public Criteria andREJTYPEBetween(String value1, String value2) {
            addCriterion("REJTYPE between", value1, value2, "REJTYPE");
            return (Criteria) this;
        }

        public Criteria andREJTYPENotBetween(String value1, String value2) {
            addCriterion("REJTYPE not between", value1, value2, "REJTYPE");
            return (Criteria) this;
        }

        public Criteria andPROTOCOLTYPEIsNull() {
            addCriterion("PROTOCOLTYPE is null");
            return (Criteria) this;
        }

        public Criteria andPROTOCOLTYPEIsNotNull() {
            addCriterion("PROTOCOLTYPE is not null");
            return (Criteria) this;
        }

        public Criteria andPROTOCOLTYPEEqualTo(String value) {
            addCriterion("PROTOCOLTYPE =", value, "PROTOCOLTYPE");
            return (Criteria) this;
        }

        public Criteria andPROTOCOLTYPENotEqualTo(String value) {
            addCriterion("PROTOCOLTYPE <>", value, "PROTOCOLTYPE");
            return (Criteria) this;
        }

        public Criteria andPROTOCOLTYPEGreaterThan(String value) {
            addCriterion("PROTOCOLTYPE >", value, "PROTOCOLTYPE");
            return (Criteria) this;
        }

        public Criteria andPROTOCOLTYPEGreaterThanOrEqualTo(String value) {
            addCriterion("PROTOCOLTYPE >=", value, "PROTOCOLTYPE");
            return (Criteria) this;
        }

        public Criteria andPROTOCOLTYPELessThan(String value) {
            addCriterion("PROTOCOLTYPE <", value, "PROTOCOLTYPE");
            return (Criteria) this;
        }

        public Criteria andPROTOCOLTYPELessThanOrEqualTo(String value) {
            addCriterion("PROTOCOLTYPE <=", value, "PROTOCOLTYPE");
            return (Criteria) this;
        }

        public Criteria andPROTOCOLTYPELike(String value) {
            addCriterion("PROTOCOLTYPE like", value, "PROTOCOLTYPE");
            return (Criteria) this;
        }

        public Criteria andPROTOCOLTYPENotLike(String value) {
            addCriterion("PROTOCOLTYPE not like", value, "PROTOCOLTYPE");
            return (Criteria) this;
        }

        public Criteria andPROTOCOLTYPEIn(List<String> values) {
            addCriterion("PROTOCOLTYPE in", values, "PROTOCOLTYPE");
            return (Criteria) this;
        }

        public Criteria andPROTOCOLTYPENotIn(List<String> values) {
            addCriterion("PROTOCOLTYPE not in", values, "PROTOCOLTYPE");
            return (Criteria) this;
        }

        public Criteria andPROTOCOLTYPEBetween(String value1, String value2) {
            addCriterion("PROTOCOLTYPE between", value1, value2, "PROTOCOLTYPE");
            return (Criteria) this;
        }

        public Criteria andPROTOCOLTYPENotBetween(String value1, String value2) {
            addCriterion("PROTOCOLTYPE not between", value1, value2, "PROTOCOLTYPE");
            return (Criteria) this;
        }

        public Criteria andLOGFILENAMEIsNull() {
            addCriterion("LOGFILENAME is null");
            return (Criteria) this;
        }

        public Criteria andLOGFILENAMEIsNotNull() {
            addCriterion("LOGFILENAME is not null");
            return (Criteria) this;
        }

        public Criteria andLOGFILENAMEEqualTo(String value) {
            addCriterion("LOGFILENAME =", value, "LOGFILENAME");
            return (Criteria) this;
        }

        public Criteria andLOGFILENAMENotEqualTo(String value) {
            addCriterion("LOGFILENAME <>", value, "LOGFILENAME");
            return (Criteria) this;
        }

        public Criteria andLOGFILENAMEGreaterThan(String value) {
            addCriterion("LOGFILENAME >", value, "LOGFILENAME");
            return (Criteria) this;
        }

        public Criteria andLOGFILENAMEGreaterThanOrEqualTo(String value) {
            addCriterion("LOGFILENAME >=", value, "LOGFILENAME");
            return (Criteria) this;
        }

        public Criteria andLOGFILENAMELessThan(String value) {
            addCriterion("LOGFILENAME <", value, "LOGFILENAME");
            return (Criteria) this;
        }

        public Criteria andLOGFILENAMELessThanOrEqualTo(String value) {
            addCriterion("LOGFILENAME <=", value, "LOGFILENAME");
            return (Criteria) this;
        }

        public Criteria andLOGFILENAMELike(String value) {
            addCriterion("LOGFILENAME like", value, "LOGFILENAME");
            return (Criteria) this;
        }

        public Criteria andLOGFILENAMENotLike(String value) {
            addCriterion("LOGFILENAME not like", value, "LOGFILENAME");
            return (Criteria) this;
        }

        public Criteria andLOGFILENAMEIn(List<String> values) {
            addCriterion("LOGFILENAME in", values, "LOGFILENAME");
            return (Criteria) this;
        }

        public Criteria andLOGFILENAMENotIn(List<String> values) {
            addCriterion("LOGFILENAME not in", values, "LOGFILENAME");
            return (Criteria) this;
        }

        public Criteria andLOGFILENAMEBetween(String value1, String value2) {
            addCriterion("LOGFILENAME between", value1, value2, "LOGFILENAME");
            return (Criteria) this;
        }

        public Criteria andLOGFILENAMENotBetween(String value1, String value2) {
            addCriterion("LOGFILENAME not between", value1, value2, "LOGFILENAME");
            return (Criteria) this;
        }

        public Criteria andHTTPPATHIsNull() {
            addCriterion("HTTPPATH is null");
            return (Criteria) this;
        }

        public Criteria andHTTPPATHIsNotNull() {
            addCriterion("HTTPPATH is not null");
            return (Criteria) this;
        }

        public Criteria andHTTPPATHEqualTo(String value) {
            addCriterion("HTTPPATH =", value, "HTTPPATH");
            return (Criteria) this;
        }

        public Criteria andHTTPPATHNotEqualTo(String value) {
            addCriterion("HTTPPATH <>", value, "HTTPPATH");
            return (Criteria) this;
        }

        public Criteria andHTTPPATHGreaterThan(String value) {
            addCriterion("HTTPPATH >", value, "HTTPPATH");
            return (Criteria) this;
        }

        public Criteria andHTTPPATHGreaterThanOrEqualTo(String value) {
            addCriterion("HTTPPATH >=", value, "HTTPPATH");
            return (Criteria) this;
        }

        public Criteria andHTTPPATHLessThan(String value) {
            addCriterion("HTTPPATH <", value, "HTTPPATH");
            return (Criteria) this;
        }

        public Criteria andHTTPPATHLessThanOrEqualTo(String value) {
            addCriterion("HTTPPATH <=", value, "HTTPPATH");
            return (Criteria) this;
        }

        public Criteria andHTTPPATHLike(String value) {
            addCriterion("HTTPPATH like", value, "HTTPPATH");
            return (Criteria) this;
        }

        public Criteria andHTTPPATHNotLike(String value) {
            addCriterion("HTTPPATH not like", value, "HTTPPATH");
            return (Criteria) this;
        }

        public Criteria andHTTPPATHIn(List<String> values) {
            addCriterion("HTTPPATH in", values, "HTTPPATH");
            return (Criteria) this;
        }

        public Criteria andHTTPPATHNotIn(List<String> values) {
            addCriterion("HTTPPATH not in", values, "HTTPPATH");
            return (Criteria) this;
        }

        public Criteria andHTTPPATHBetween(String value1, String value2) {
            addCriterion("HTTPPATH between", value1, value2, "HTTPPATH");
            return (Criteria) this;
        }

        public Criteria andHTTPPATHNotBetween(String value1, String value2) {
            addCriterion("HTTPPATH not between", value1, value2, "HTTPPATH");
            return (Criteria) this;
        }

        public Criteria andOFLAGIsNull() {
            addCriterion("OFLAG is null");
            return (Criteria) this;
        }

        public Criteria andOFLAGIsNotNull() {
            addCriterion("OFLAG is not null");
            return (Criteria) this;
        }

        public Criteria andOFLAGEqualTo(String value) {
            addCriterion("OFLAG =", value, "OFLAG");
            return (Criteria) this;
        }

        public Criteria andOFLAGNotEqualTo(String value) {
            addCriterion("OFLAG <>", value, "OFLAG");
            return (Criteria) this;
        }

        public Criteria andOFLAGGreaterThan(String value) {
            addCriterion("OFLAG >", value, "OFLAG");
            return (Criteria) this;
        }

        public Criteria andOFLAGGreaterThanOrEqualTo(String value) {
            addCriterion("OFLAG >=", value, "OFLAG");
            return (Criteria) this;
        }

        public Criteria andOFLAGLessThan(String value) {
            addCriterion("OFLAG <", value, "OFLAG");
            return (Criteria) this;
        }

        public Criteria andOFLAGLessThanOrEqualTo(String value) {
            addCriterion("OFLAG <=", value, "OFLAG");
            return (Criteria) this;
        }

        public Criteria andOFLAGLike(String value) {
            addCriterion("OFLAG like", value, "OFLAG");
            return (Criteria) this;
        }

        public Criteria andOFLAGNotLike(String value) {
            addCriterion("OFLAG not like", value, "OFLAG");
            return (Criteria) this;
        }

        public Criteria andOFLAGIn(List<String> values) {
            addCriterion("OFLAG in", values, "OFLAG");
            return (Criteria) this;
        }

        public Criteria andOFLAGNotIn(List<String> values) {
            addCriterion("OFLAG not in", values, "OFLAG");
            return (Criteria) this;
        }

        public Criteria andOFLAGBetween(String value1, String value2) {
            addCriterion("OFLAG between", value1, value2, "OFLAG");
            return (Criteria) this;
        }

        public Criteria andOFLAGNotBetween(String value1, String value2) {
            addCriterion("OFLAG not between", value1, value2, "OFLAG");
            return (Criteria) this;
        }

        public Criteria andPORTIsNull() {
            addCriterion("PORT is null");
            return (Criteria) this;
        }

        public Criteria andPORTIsNotNull() {
            addCriterion("PORT is not null");
            return (Criteria) this;
        }

        public Criteria andPORTEqualTo(String value) {
            addCriterion("PORT =", value, "PORT");
            return (Criteria) this;
        }

        public Criteria andPORTNotEqualTo(String value) {
            addCriterion("PORT <>", value, "PORT");
            return (Criteria) this;
        }

        public Criteria andPORTGreaterThan(String value) {
            addCriterion("PORT >", value, "PORT");
            return (Criteria) this;
        }

        public Criteria andPORTGreaterThanOrEqualTo(String value) {
            addCriterion("PORT >=", value, "PORT");
            return (Criteria) this;
        }

        public Criteria andPORTLessThan(String value) {
            addCriterion("PORT <", value, "PORT");
            return (Criteria) this;
        }

        public Criteria andPORTLessThanOrEqualTo(String value) {
            addCriterion("PORT <=", value, "PORT");
            return (Criteria) this;
        }

        public Criteria andPORTLike(String value) {
            addCriterion("PORT like", value, "PORT");
            return (Criteria) this;
        }

        public Criteria andPORTNotLike(String value) {
            addCriterion("PORT not like", value, "PORT");
            return (Criteria) this;
        }

        public Criteria andPORTIn(List<String> values) {
            addCriterion("PORT in", values, "PORT");
            return (Criteria) this;
        }

        public Criteria andPORTNotIn(List<String> values) {
            addCriterion("PORT not in", values, "PORT");
            return (Criteria) this;
        }

        public Criteria andPORTBetween(String value1, String value2) {
            addCriterion("PORT between", value1, value2, "PORT");
            return (Criteria) this;
        }

        public Criteria andPORTNotBetween(String value1, String value2) {
            addCriterion("PORT not between", value1, value2, "PORT");
            return (Criteria) this;
        }

        public Criteria andRECEPTTYPEIsNull() {
            addCriterion("RECEPTTYPE is null");
            return (Criteria) this;
        }

        public Criteria andRECEPTTYPEIsNotNull() {
            addCriterion("RECEPTTYPE is not null");
            return (Criteria) this;
        }

        public Criteria andRECEPTTYPEEqualTo(String value) {
            addCriterion("RECEPTTYPE =", value, "RECEPTTYPE");
            return (Criteria) this;
        }

        public Criteria andRECEPTTYPENotEqualTo(String value) {
            addCriterion("RECEPTTYPE <>", value, "RECEPTTYPE");
            return (Criteria) this;
        }

        public Criteria andRECEPTTYPEGreaterThan(String value) {
            addCriterion("RECEPTTYPE >", value, "RECEPTTYPE");
            return (Criteria) this;
        }

        public Criteria andRECEPTTYPEGreaterThanOrEqualTo(String value) {
            addCriterion("RECEPTTYPE >=", value, "RECEPTTYPE");
            return (Criteria) this;
        }

        public Criteria andRECEPTTYPELessThan(String value) {
            addCriterion("RECEPTTYPE <", value, "RECEPTTYPE");
            return (Criteria) this;
        }

        public Criteria andRECEPTTYPELessThanOrEqualTo(String value) {
            addCriterion("RECEPTTYPE <=", value, "RECEPTTYPE");
            return (Criteria) this;
        }

        public Criteria andRECEPTTYPELike(String value) {
            addCriterion("RECEPTTYPE like", value, "RECEPTTYPE");
            return (Criteria) this;
        }

        public Criteria andRECEPTTYPENotLike(String value) {
            addCriterion("RECEPTTYPE not like", value, "RECEPTTYPE");
            return (Criteria) this;
        }

        public Criteria andRECEPTTYPEIn(List<String> values) {
            addCriterion("RECEPTTYPE in", values, "RECEPTTYPE");
            return (Criteria) this;
        }

        public Criteria andRECEPTTYPENotIn(List<String> values) {
            addCriterion("RECEPTTYPE not in", values, "RECEPTTYPE");
            return (Criteria) this;
        }

        public Criteria andRECEPTTYPEBetween(String value1, String value2) {
            addCriterion("RECEPTTYPE between", value1, value2, "RECEPTTYPE");
            return (Criteria) this;
        }

        public Criteria andRECEPTTYPENotBetween(String value1, String value2) {
            addCriterion("RECEPTTYPE not between", value1, value2, "RECEPTTYPE");
            return (Criteria) this;
        }

        public Criteria andSESSIONTIMELENGTHIsNull() {
            addCriterion("SESSIONTIMELENGTH is null");
            return (Criteria) this;
        }

        public Criteria andSESSIONTIMELENGTHIsNotNull() {
            addCriterion("SESSIONTIMELENGTH is not null");
            return (Criteria) this;
        }

        public Criteria andSESSIONTIMELENGTHEqualTo(BigDecimal value) {
            addCriterion("SESSIONTIMELENGTH =", value, "SESSIONTIMELENGTH");
            return (Criteria) this;
        }

        public Criteria andSESSIONTIMELENGTHNotEqualTo(BigDecimal value) {
            addCriterion("SESSIONTIMELENGTH <>", value, "SESSIONTIMELENGTH");
            return (Criteria) this;
        }

        public Criteria andSESSIONTIMELENGTHGreaterThan(BigDecimal value) {
            addCriterion("SESSIONTIMELENGTH >", value, "SESSIONTIMELENGTH");
            return (Criteria) this;
        }

        public Criteria andSESSIONTIMELENGTHGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("SESSIONTIMELENGTH >=", value, "SESSIONTIMELENGTH");
            return (Criteria) this;
        }

        public Criteria andSESSIONTIMELENGTHLessThan(BigDecimal value) {
            addCriterion("SESSIONTIMELENGTH <", value, "SESSIONTIMELENGTH");
            return (Criteria) this;
        }

        public Criteria andSESSIONTIMELENGTHLessThanOrEqualTo(BigDecimal value) {
            addCriterion("SESSIONTIMELENGTH <=", value, "SESSIONTIMELENGTH");
            return (Criteria) this;
        }

        public Criteria andSESSIONTIMELENGTHIn(List<BigDecimal> values) {
            addCriterion("SESSIONTIMELENGTH in", values, "SESSIONTIMELENGTH");
            return (Criteria) this;
        }

        public Criteria andSESSIONTIMELENGTHNotIn(List<BigDecimal> values) {
            addCriterion("SESSIONTIMELENGTH not in", values, "SESSIONTIMELENGTH");
            return (Criteria) this;
        }

        public Criteria andSESSIONTIMELENGTHBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SESSIONTIMELENGTH between", value1, value2, "SESSIONTIMELENGTH");
            return (Criteria) this;
        }

        public Criteria andSESSIONTIMELENGTHNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SESSIONTIMELENGTH not between", value1, value2, "SESSIONTIMELENGTH");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TLOG_HOSTINFO
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table TLOG_HOSTINFO
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}