package com.bizwink.po;

import java.math.BigDecimal;
import java.util.Date;

public class LogStatisticInHour {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TLOG_STATISTIC_IN_HOUR.ID
     *
     * @mbggenerated
     */
    private BigDecimal ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TLOG_STATISTIC_IN_HOUR.DOMAINID
     *
     * @mbggenerated
     */
    private BigDecimal DOMAINID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TLOG_STATISTIC_IN_HOUR.HOSTID
     *
     * @mbggenerated
     */
    private BigDecimal HOSTID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TLOG_STATISTIC_IN_HOUR.AHOUR
     *
     * @mbggenerated
     */
    private BigDecimal AHOUR;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TLOG_STATISTIC_IN_HOUR.PVS
     *
     * @mbggenerated
     */
    private BigDecimal PVS;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TLOG_STATISTIC_IN_HOUR.UVS
     *
     * @mbggenerated
     */
    private BigDecimal UVS;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TLOG_STATISTIC_IN_HOUR.HITS
     *
     * @mbggenerated
     */
    private BigDecimal HITS;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TLOG_STATISTIC_IN_HOUR.BYTES
     *
     * @mbggenerated
     */
    private BigDecimal BYTES;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TLOG_STATISTIC_IN_HOUR.LOGDATE
     *
     * @mbggenerated
     */
    private Date LOGDATE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TLOG_STATISTIC_IN_HOUR.IPS
     *
     * @mbggenerated
     */
    private BigDecimal IPS;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TLOG_STATISTIC_IN_HOUR.SESSIONS
     *
     * @mbggenerated
     */
    private BigDecimal SESSIONS;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TLOG_STATISTIC_IN_HOUR.ID
     *
     * @return the value of TLOG_STATISTIC_IN_HOUR.ID
     *
     * @mbggenerated
     */
    public BigDecimal getID() {
        return ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TLOG_STATISTIC_IN_HOUR.ID
     *
     * @param ID the value for TLOG_STATISTIC_IN_HOUR.ID
     *
     * @mbggenerated
     */
    public void setID(BigDecimal ID) {
        this.ID = ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TLOG_STATISTIC_IN_HOUR.DOMAINID
     *
     * @return the value of TLOG_STATISTIC_IN_HOUR.DOMAINID
     *
     * @mbggenerated
     */
    public BigDecimal getDOMAINID() {
        return DOMAINID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TLOG_STATISTIC_IN_HOUR.DOMAINID
     *
     * @param DOMAINID the value for TLOG_STATISTIC_IN_HOUR.DOMAINID
     *
     * @mbggenerated
     */
    public void setDOMAINID(BigDecimal DOMAINID) {
        this.DOMAINID = DOMAINID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TLOG_STATISTIC_IN_HOUR.HOSTID
     *
     * @return the value of TLOG_STATISTIC_IN_HOUR.HOSTID
     *
     * @mbggenerated
     */
    public BigDecimal getHOSTID() {
        return HOSTID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TLOG_STATISTIC_IN_HOUR.HOSTID
     *
     * @param HOSTID the value for TLOG_STATISTIC_IN_HOUR.HOSTID
     *
     * @mbggenerated
     */
    public void setHOSTID(BigDecimal HOSTID) {
        this.HOSTID = HOSTID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TLOG_STATISTIC_IN_HOUR.AHOUR
     *
     * @return the value of TLOG_STATISTIC_IN_HOUR.AHOUR
     *
     * @mbggenerated
     */
    public BigDecimal getAHOUR() {
        return AHOUR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TLOG_STATISTIC_IN_HOUR.AHOUR
     *
     * @param AHOUR the value for TLOG_STATISTIC_IN_HOUR.AHOUR
     *
     * @mbggenerated
     */
    public void setAHOUR(BigDecimal AHOUR) {
        this.AHOUR = AHOUR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TLOG_STATISTIC_IN_HOUR.PVS
     *
     * @return the value of TLOG_STATISTIC_IN_HOUR.PVS
     *
     * @mbggenerated
     */
    public BigDecimal getPVS() {
        return PVS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TLOG_STATISTIC_IN_HOUR.PVS
     *
     * @param PVS the value for TLOG_STATISTIC_IN_HOUR.PVS
     *
     * @mbggenerated
     */
    public void setPVS(BigDecimal PVS) {
        this.PVS = PVS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TLOG_STATISTIC_IN_HOUR.UVS
     *
     * @return the value of TLOG_STATISTIC_IN_HOUR.UVS
     *
     * @mbggenerated
     */
    public BigDecimal getUVS() {
        return UVS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TLOG_STATISTIC_IN_HOUR.UVS
     *
     * @param UVS the value for TLOG_STATISTIC_IN_HOUR.UVS
     *
     * @mbggenerated
     */
    public void setUVS(BigDecimal UVS) {
        this.UVS = UVS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TLOG_STATISTIC_IN_HOUR.HITS
     *
     * @return the value of TLOG_STATISTIC_IN_HOUR.HITS
     *
     * @mbggenerated
     */
    public BigDecimal getHITS() {
        return HITS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TLOG_STATISTIC_IN_HOUR.HITS
     *
     * @param HITS the value for TLOG_STATISTIC_IN_HOUR.HITS
     *
     * @mbggenerated
     */
    public void setHITS(BigDecimal HITS) {
        this.HITS = HITS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TLOG_STATISTIC_IN_HOUR.BYTES
     *
     * @return the value of TLOG_STATISTIC_IN_HOUR.BYTES
     *
     * @mbggenerated
     */
    public BigDecimal getBYTES() {
        return BYTES;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TLOG_STATISTIC_IN_HOUR.BYTES
     *
     * @param BYTES the value for TLOG_STATISTIC_IN_HOUR.BYTES
     *
     * @mbggenerated
     */
    public void setBYTES(BigDecimal BYTES) {
        this.BYTES = BYTES;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TLOG_STATISTIC_IN_HOUR.LOGDATE
     *
     * @return the value of TLOG_STATISTIC_IN_HOUR.LOGDATE
     *
     * @mbggenerated
     */
    public Date getLOGDATE() {
        return LOGDATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TLOG_STATISTIC_IN_HOUR.LOGDATE
     *
     * @param LOGDATE the value for TLOG_STATISTIC_IN_HOUR.LOGDATE
     *
     * @mbggenerated
     */
    public void setLOGDATE(Date LOGDATE) {
        this.LOGDATE = LOGDATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TLOG_STATISTIC_IN_HOUR.IPS
     *
     * @return the value of TLOG_STATISTIC_IN_HOUR.IPS
     *
     * @mbggenerated
     */
    public BigDecimal getIPS() {
        return IPS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TLOG_STATISTIC_IN_HOUR.IPS
     *
     * @param IPS the value for TLOG_STATISTIC_IN_HOUR.IPS
     *
     * @mbggenerated
     */
    public void setIPS(BigDecimal IPS) {
        this.IPS = IPS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TLOG_STATISTIC_IN_HOUR.SESSIONS
     *
     * @return the value of TLOG_STATISTIC_IN_HOUR.SESSIONS
     *
     * @mbggenerated
     */
    public BigDecimal getSESSIONS() {
        return SESSIONS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TLOG_STATISTIC_IN_HOUR.SESSIONS
     *
     * @param SESSIONS the value for TLOG_STATISTIC_IN_HOUR.SESSIONS
     *
     * @mbggenerated
     */
    public void setSESSIONS(BigDecimal SESSIONS) {
        this.SESSIONS = SESSIONS;
    }
}