/*
 * JSP generated by Resin-4.0.58 (built Fri, 24 Aug 2018 01:23:14 PDT)
 */

package _jsp._upload;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.util.*;
import com.bizwink.cms.sitesetting.*;
import com.bizwink.upload.*;
import com.bizwink.cms.tree.*;
import com.bizwink.cms.security.*;
import com.bizwink.cms.util.*;

public class _modelupload2__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  private boolean _caucho_isNotModified;
  private com.caucho.jsp.PageManager _jsp_pageManager;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    com.caucho.jsp.PageContextImpl pageContext = _jsp_pageManager.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);

    TagState _jsp_state = null;

    try {
      _jspService(request, response, pageContext, _jsp_application, session, _jsp_state);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_pageManager.freePageContext(pageContext);
    }
  }
  
  private void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response,
              com.caucho.jsp.PageContextImpl pageContext,
              javax.servlet.ServletContext application,
              javax.servlet.http.HttpSession session,
              TagState _jsp_state)
    throws Throwable
  {
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.jsp.tagext.JspTag _jsp_parent_tag = null;
    com.caucho.jsp.PageContextImpl _jsp_parentContext = pageContext;
    response.setContentType("text/html;charset=utf-8");

    out.write(_jsp_string0, 0, _jsp_string0.length);
    
    Auth authToken = SessionUtil.getUserAuthorization(request, response, session);
    if (authToken == null) {
        response.sendRedirect(response.encodeRedirectURL("../login.jsp?msg=\u7cfb\u7edf\u8d85\u65f6\uff0c\u8bf7\u91cd\u65b0\u767b\u9646!"));
        return;
    }
    int siteid = authToken.getSiteID();
    int cssjsdir = authToken.getCssJsDir();
    String username = authToken.getUserID();
    String sitename = authToken.getSitename();
    int imgflag = authToken.getImgSaveFlag();
    int tcflag = authToken.getPublishFlag();
    String fileDir = "";
    String dir = "";

    Tree colTree = TreeManager.getInstance().getSiteTree(siteid);
    int columnID = ParamUtil.getIntParameter(request, "column", 0);
    if (columnID == colTree.getTreeRoot())
        fileDir = java.io.File.separator;
    else
        fileDir = colTree.getDirName(colTree, columnID);

    String baseDir = application.getRealPath("/");
    String tempDir = StringUtil.replace(fileDir, "/", java.io.File.separator);

    //\u53bb\u6389\u8fd4\u56de\u76ee\u5f55\u4e2d\u7684\u57df\u540d
    String sitenameBuf = StringUtil.replace(sitename, "_", ".");
    int posi = tempDir.indexOf(sitenameBuf);
    if (posi != -1) tempDir = tempDir.substring(posi + sitenameBuf.length());
    dir = baseDir + "sites" + java.io.File.separator + sitename;

    //\u83b7\u5f97\u6240\u6709\u53d1\u5e03\u4e3b\u673a\u5217\u8868
    IFtpSetManager ftpsetMgr = FtpSetting.getInstance();
    List siteList = ftpsetMgr.getOtherFtpInfos(siteid);

    out.write(_jsp_string1, 0, _jsp_string1.length);
    out.print((request.getContextPath()));
    out.write(_jsp_string2, 0, _jsp_string2.length);
    out.print((dir));
    out.write(_jsp_string3, 0, _jsp_string3.length);
    out.print((MultipartFormHandle.FORWARDNAME));
    out.write(_jsp_string4, 0, _jsp_string4.length);
    out.print((columnID));
    out.write(_jsp_string5, 0, _jsp_string5.length);
    out.print((baseDir));
    out.write(_jsp_string6, 0, _jsp_string6.length);
    out.print((tempDir));
    out.write(_jsp_string7, 0, _jsp_string7.length);
    out.print((sitename));
    out.write(_jsp_string8, 0, _jsp_string8.length);
    out.print((siteid));
    out.write(_jsp_string9, 0, _jsp_string9.length);
    out.print((username));
    out.write(_jsp_string10, 0, _jsp_string10.length);
    out.print((imgflag));
    out.write(_jsp_string11, 0, _jsp_string11.length);
    out.print((cssjsdir));
    out.write(_jsp_string12, 0, _jsp_string12.length);
    out.print((tcflag));
    out.write(_jsp_string13, 0, _jsp_string13.length);
    if(tcflag == 1){
    out.write(_jsp_string14, 0, _jsp_string14.length);
    }
    out.write(_jsp_string15, 0, _jsp_string15.length);
    
                    for (int i = 0; i < siteList.size(); i++) {
                        FtpInfo ftpinfo = (FtpInfo) siteList.get(i);
                        if (ftpinfo.getStatus() == 0) {
                            String siteName = ftpinfo.getSiteName();
                            if (siteName == null || siteName.length() == 0) siteName = sitename;
                
    out.write(_jsp_string16, 0, _jsp_string16.length);
    out.print((ftpinfo.getID()));
    out.write(_jsp_string17, 0, _jsp_string17.length);
    out.print((siteName));
    out.write(_jsp_string18, 0, _jsp_string18.length);
    
                        }
                    }
                
    out.write(_jsp_string19, 0, _jsp_string19.length);
  }

  private com.caucho.make.DependencyContainer _caucho_depends
    = new com.caucho.make.DependencyContainer();

  public java.util.ArrayList<com.caucho.vfs.Dependency> _caucho_getDependList()
  {
    return _caucho_depends.getDependencies();
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    _caucho_depends.add(depend);
  }

  protected void _caucho_setNeverModified(boolean isNotModified)
  {
    _caucho_isNotModified = true;
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;

    if (_caucho_isNotModified)
      return false;

    if (com.caucho.server.util.CauchoSystem.getVersionId() != 6165118203484593848L)
      return true;

    return _caucho_depends.isModified();
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
    TagState tagState;
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("upload/modelupload2.jsp"), -2309752001921377554L, false);
    _caucho_depends.add(depend);
    loader.addDependency(depend);
  }

  final static class TagState {

    void release()
    {
    }
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void caucho_init(ServletConfig config)
  {
    try {
      com.caucho.server.webapp.WebApp webApp
        = (com.caucho.server.webapp.WebApp) config.getServletContext();
      init(config);
      if (com.caucho.jsp.JspManager.getCheckInterval() >= 0)
        _caucho_depends.setCheckInterval(com.caucho.jsp.JspManager.getCheckInterval());
      _jsp_pageManager = webApp.getJspApplicationContext().getPageManager();
      com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
      com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.InitPageContextImpl(webApp, this);
    } catch (Exception e) {
      throw com.caucho.config.ConfigException.create(e);
    }
  }

  private final static char []_jsp_string16;
  private final static char []_jsp_string13;
  private final static char []_jsp_string4;
  private final static char []_jsp_string9;
  private final static char []_jsp_string7;
  private final static char []_jsp_string12;
  private final static char []_jsp_string10;
  private final static char []_jsp_string17;
  private final static char []_jsp_string5;
  private final static char []_jsp_string14;
  private final static char []_jsp_string6;
  private final static char []_jsp_string11;
  private final static char []_jsp_string15;
  private final static char []_jsp_string2;
  private final static char []_jsp_string3;
  private final static char []_jsp_string0;
  private final static char []_jsp_string19;
  private final static char []_jsp_string1;
  private final static char []_jsp_string8;
  private final static char []_jsp_string18;
  static {
    _jsp_string16 = "\r\n                <option value=\"".toCharArray();
    _jsp_string13 = "\">\r\n    <TABLE CELLSPACING=10 align=center width=\"100%\">\r\n        <tr>\r\n            <td>\u7b80\u4f53\u6587\u4ef6\uff1a<INPUT type=file ID=sfilename name=sfilename size=30></td>\r\n        </tr>\r\n        ".toCharArray();
    _jsp_string4 = "\" value=\"/upload/modelupload2.jsp\">\r\n    <input type=\"hidden\" name=\"column\" value=\"".toCharArray();
    _jsp_string9 = "\">\r\n    <input type=\"hidden\" name=\"username\" value=\"".toCharArray();
    _jsp_string7 = "\">\r\n    <input type=\"hidden\" name=\"sitename\" value=\"".toCharArray();
    _jsp_string12 = "\">\r\n    <input type=\"hidden\" name=\"tcflag\" value=\"".toCharArray();
    _jsp_string10 = "\">\r\n    <input type=\"hidden\" name=\"imgflag\" value=\"".toCharArray();
    _jsp_string17 = "\">".toCharArray();
    _jsp_string5 = "\">\r\n    <input type=\"hidden\" name=\"baseDir\" value=\"".toCharArray();
    _jsp_string14 = "\r\n        <tr>\r\n            <td>\u7e41\u4f53\u6587\u4ef6\uff1a<INPUT type=file ID=tfilename name=tfilename size=30></td>\r\n        </tr>\r\n        ".toCharArray();
    _jsp_string6 = "\">\r\n    <input type=\"hidden\" name=\"fileDir\" value=\"".toCharArray();
    _jsp_string11 = "\">\r\n    <input type=\"hidden\" name=\"fromflag\" value=\"model\">\r\n    <input type=\"hidden\" name=\"cssjsdir\" value=\"".toCharArray();
    _jsp_string15 = "\r\n        <tr>\r\n            <td>\u9009\u62e9\u4e3b\u673a\uff1a<select name=\"hostID\" size=1 style=\"width:185;font-size:9pt\">\r\n                <option value=\"0\" selected>\u9ed8\u8ba4\u53d1\u5e03\u4e3b\u673a</option>\r\n                ".toCharArray();
    _jsp_string2 = "/multipartformserv?dir=".toCharArray();
    _jsp_string3 = "\" name=uploadfile\r\n      enctype=\"multipart/form-data\" onSubmit=\"return validate();\">\r\n    <input type=\"hidden\" name=\"".toCharArray();
    _jsp_string0 = "\r\n".toCharArray();
    _jsp_string19 = "</select>\r\n            </td>\r\n        </tr>\r\n        <TR height=40>\r\n            <TD align=center>\r\n                <input type=\"submit\" name=ok value=\"  \u786e\u5b9a  \" class=tine>&nbsp;&nbsp;\r\n                <input type=\"button\" name=Cancel onclick=\"window.close();\" value=\"  \u53d6\u6d88  \" class=tine>\r\n            </TD>\r\n        </TR>\r\n    </TABLE>\r\n</FORM>\r\n\r\n</BODY>\r\n</HTML>".toCharArray();
    _jsp_string1 = "\r\n\r\n<HTML>\r\n<HEAD>\r\n    <TITLE>\u4e0a\u4f20\u65b0\u6a21\u677f/\u56fe\u50cf</TITLE>\r\n    <link rel=stylesheet type=\"text/css\" href=\"/webbuilder/style/global.css\">\r\n    <meta http-equiv=Content-Type content=\"text/html; charset=utf-8\">\r\n    <SCRIPT LANGUAGE=\"JavaScript\">\r\n        function validate()\r\n        {\r\n            if (uploadfile.sfilename.value == \"\" || uploadfile.sfilename.value == null)\r\n            {\r\n                alert(\"\u8bf7\u9009\u62e9\u8981\u4e0a\u4f20\u6587\u4ef6\");\r\n                uploadfile.sfilename.focus();\r\n                return false;\r\n            }\r\n            return true;\r\n        }\r\n    </SCRIPT>\r\n</HEAD>\r\n\r\n<BODY bgcolor=\"#cccccc\">\r\n<form method=\"post\" action=\"".toCharArray();
    _jsp_string8 = "\">\r\n    <input type=\"hidden\" name=\"siteid\" value=\"".toCharArray();
    _jsp_string18 = "\r\n                </option>\r\n                ".toCharArray();
  }
}
