/*
 * JSP generated by Resin-4.0.58 (built Fri, 24 Aug 2018 01:23:14 PDT)
 */

package _jsp._toolkit._survey;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import com.bizwink.cms.util.ParamUtil;
import com.bizwink.webapps.survey.define.DefineException;
import com.bizwink.webapps.survey.define.DefinePeer;
import com.bizwink.cms.security.Auth;
import com.bizwink.cms.util.StringUtil;
import com.bizwink.webapps.survey.define.IDefineManager;
import com.bizwink.cms.util.SessionUtil;
import com.bizwink.webapps.survey.define.Define;

public class _updatesurvey__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  private boolean _caucho_isNotModified;
  private com.caucho.jsp.PageManager _jsp_pageManager;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    com.caucho.jsp.PageContextImpl pageContext = _jsp_pageManager.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);

    TagState _jsp_state = null;

    try {
      _jspService(request, response, pageContext, _jsp_application, session, _jsp_state);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_pageManager.freePageContext(pageContext);
    }
  }
  
  private void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response,
              com.caucho.jsp.PageContextImpl pageContext,
              javax.servlet.ServletContext application,
              javax.servlet.http.HttpSession session,
              TagState _jsp_state)
    throws Throwable
  {
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.jsp.tagext.JspTag _jsp_parent_tag = null;
    com.caucho.jsp.PageContextImpl _jsp_parentContext = pageContext;
    response.setContentType("text/html;charset=GBK");

    out.write(_jsp_string0, 0, _jsp_string0.length);
    
    Auth authToken = SessionUtil.getUserAuthorization(request, response, session);
    if (authToken == null) {
        response.sendRedirect(response.encodeRedirectURL("../../login.jsp?msg=\u7cfb\u7edf\u8d85\u65f6\uff0c\u8bf7\u91cd\u65b0\u767b\u9646!"));
        return;
    }
  int sid = ParamUtil.getIntParameter(request, "sid", -1);
  int startflag = ParamUtil.getIntParameter(request, "startflag", -1);

  String surveyname = "";
  String notes = "";

  IDefineManager defineMgr = DefinePeer.getInstance();
  Define define = new Define();

  if (sid != -1) {
    try {
      define = defineMgr.getADefineSurvey(sid);
      surveyname = define.getSurveyname();
      notes = define.getNotes();
    } catch (DefineException e) {
      e.printStackTrace();
    }
  }

  if ((startflag == 1) && (sid != -1)) {
    surveyname = ParamUtil.getParameter(request, "surveyname");
    notes = ParamUtil.getParameter(request, "notes");

    try {
      define.setId(sid);
      define.setSurveyname(surveyname);
      define.setNotes(notes);
      defineMgr.updateDefineSurvey(define);

      response.sendRedirect("index.jsp?success=3");
    } catch (DefineException e) {
      e.printStackTrace();
    }
  }

    out.write(_jsp_string1, 0, _jsp_string1.length);
    out.print((sid));
    out.write(_jsp_string2, 0, _jsp_string2.length);
    out.print((StringUtil.iso2gb(surveyname)));
    out.write(_jsp_string3, 0, _jsp_string3.length);
    out.print((StringUtil.iso2gb(notes)));
    out.write(_jsp_string4, 0, _jsp_string4.length);
  }

  private com.caucho.make.DependencyContainer _caucho_depends
    = new com.caucho.make.DependencyContainer();

  public java.util.ArrayList<com.caucho.vfs.Dependency> _caucho_getDependList()
  {
    return _caucho_depends.getDependencies();
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    _caucho_depends.add(depend);
  }

  protected void _caucho_setNeverModified(boolean isNotModified)
  {
    _caucho_isNotModified = true;
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;

    if (_caucho_isNotModified)
      return false;

    if (com.caucho.server.util.CauchoSystem.getVersionId() != 6165118203484593848L)
      return true;

    return _caucho_depends.isModified();
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
    TagState tagState;
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("toolkit/survey/updateSurvey.jsp"), 5611906195731409097L, false);
    _caucho_depends.add(depend);
    loader.addDependency(depend);
  }

  final static class TagState {

    void release()
    {
    }
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void caucho_init(ServletConfig config)
  {
    try {
      com.caucho.server.webapp.WebApp webApp
        = (com.caucho.server.webapp.WebApp) config.getServletContext();
      init(config);
      if (com.caucho.jsp.JspManager.getCheckInterval() >= 0)
        _caucho_depends.setCheckInterval(com.caucho.jsp.JspManager.getCheckInterval());
      _jsp_pageManager = webApp.getJspApplicationContext().getPageManager();
      com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
      com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.InitPageContextImpl(webApp, this);
    } catch (Exception e) {
      throw com.caucho.config.ConfigException.create(e);
    }
  }

  private final static char []_jsp_string2;
  private final static char []_jsp_string3;
  private final static char []_jsp_string1;
  private final static char []_jsp_string4;
  private final static char []_jsp_string0;
  static {
    _jsp_string2 = "\">\r\n          <tr>\r\n            <td>\r\n              <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n                <tr>\r\n                  <td width=\"50\" height=\"40\" align=\"center\"><img src=\"images/qian_02.jpg\" width=\"30\" height=\"30\"/>\r\n                  </td>\r\n                  <td width=\"150\" class=\"black12c\">\u4fee\u6539\u8c03\u67e5</td>\r\n                  <td width=\"697\"></td>\r\n                </tr>\r\n\r\n              </table>\r\n            </td>\r\n          </tr>\r\n          <tr>\r\n            <td>\r\n              <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n                <tr>\r\n                  <td width=\"200\" height=\"1\" bgcolor=\"#898898\"></td>\r\n                  <td width=\"1\" height=\"1\" bgcolor=\"#898898\"></td>\r\n                  <td height=\"1\" bgcolor=\"#898898\"></td>\r\n                </tr>\r\n                <tr>\r\n                  <td height=\"40\" align=\"center\" bgcolor=\"#F6F5F0\" class=\"black12c\">\u8c03\u67e5\u540d\u79f0\uff1a</td>\r\n                  <td width=\"1\" bgcolor=\"#898898\"></td>\r\n                  <td>\r\n                    &nbsp;&nbsp;<input type=\"text\" name=\"surveyname\" size=\"80\"\r\n                                       value=\"".toCharArray();
    _jsp_string3 = "\">\r\n                  </td>\r\n                </tr>\r\n                <tr>\r\n                  <td height=\"1\" bgcolor=\"#898898\"></td>\r\n                  <td width=\"1\" height=\"1\" bgcolor=\"#898898\"></td>\r\n                  <td height=\"1\" bgcolor=\"#898898\"></td>\r\n                </tr>\r\n                <tr>\r\n                  <td height=\"100\" align=\"center\" bgcolor=\"#F6F5F0\" class=\"black12c\">\u8c03\u67e5\u63cf\u8ff0\uff1a</td>\r\n                  <td width=\"1\" bgcolor=\"#898898\"></td>\r\n                  <td>\r\n                    &nbsp;&nbsp;<textarea rows=\"6\" name=\"notes\"\r\n                                          cols=\"80\">".toCharArray();
    _jsp_string1 = "\r\n<html>\r\n<head>\r\n  <meta http-equiv=\"Content-Type\" content=\"text/html; charset=gb2312\"/>\r\n  <title>\u4fee\u6539\u8c03\u67e5</title>\r\n  <style type=\"text/css\">\r\n    <!--\r\n    body {\r\n      margin-top: 0px;\r\n      margin-bottom: 0px;\r\n    }\r\n\r\n    -->\r\n  </style>\r\n  <link href=\"images/css.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n  <script type=\"text/javascript\">\r\n    function checkSurvey() {\r\n      if ((addSurveyForm.surveyname.value == null) || (addSurveyForm.surveyname.value == \"\")) {\r\n        alert(\"\u8bf7\u8f93\u5165\u5b9a\u4e49\u8c03\u67e5\u7684\u540d\u79f0\");\r\n        return false;\r\n      }\r\n      if ((addSurveyForm.notes.value == null) || (addSurveyForm.notes.value == \"\")) {\r\n        alert(\"\u8bf7\u8f93\u5165\u5b9a\u4e49\u8c03\u67e5\u7684\u63cf\u8ff0\");\r\n        return false;\r\n      }\r\n      return true;\r\n    }\r\n  </script>\r\n</head>\r\n\r\n<body>\r\n<center>\r\n<table width=\"900\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"bian\">\r\n  <tr>\r\n    <td height=\"360\" valign=\"top\">\r\n      <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n        <form method=\"POST\" action=\"updateSurvey.jsp\" name=\"addSurveyForm\" onsubmit=\"javascript:return checkSurvey();\">\r\n          <input type=\"hidden\" name=\"startflag\" value=\"1\">\r\n          <input type=\"hidden\" name=\"sid\" value=\"".toCharArray();
    _jsp_string4 = "\r\n                  </textarea>\r\n                  </td>\r\n                </tr>\r\n                <tr>\r\n                  <td height=\"1\" bgcolor=\"#898898\"></td>\r\n                  <td width=\"1\" height=\"1\" bgcolor=\"#898898\"></td>\r\n                  <td height=\"1\" bgcolor=\"#898898\"></td>\r\n                </tr>\r\n              </table>\r\n            </td>\r\n          </tr>\r\n          <tr>\r\n            <td height=\"50\">\r\n              <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n                <tr>\r\n                  <td width=\"300\"></td>\r\n                  <td width=\"52\"><input type=\"submit\" value=\"\u63d0  \u4ea4\" name=\"survey_submit\"></td>\r\n                  <td width=\"70\"></td>\r\n                  <td width=\"52\"><input type=\"reset\" value=\"\u91cd  \u5199\"/></td>\r\n                  <td width=\"71\"></td>\r\n                  <td width=\"52\"><input type=\"button\" value=\"\u8fd4  \u56de\" name=\"survey_reset\"\r\n                                        onclick=\"window.location='index.jsp'\"></td>\r\n                  <td width=\"300\"></td>\r\n                </tr>\r\n              </table>\r\n            </td>\r\n          </tr>\r\n        </form>\r\n      </table>\r\n    </td>\r\n  </tr>\r\n</table>\r\n</center>\r\n</body>\r\n</html>\r\n\r\n\r\n".toCharArray();
    _jsp_string0 = "\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n".toCharArray();
  }
}
