package com.bizwink.po;

import java.math.BigDecimal;

public class LogBrowsername {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TLOG_BROWSERNAME.ID
     *
     * @mbggenerated
     */
    private BigDecimal ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TLOG_BROWSERNAME.BROWSERNAME
     *
     * @mbggenerated
     */
    private String BROWSERNAME;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TLOG_BROWSERNAME.ID
     *
     * @return the value of TLOG_BROWSERNAME.ID
     *
     * @mbggenerated
     */
    public BigDecimal getID() {
        return ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TLOG_BROWSERNAME.ID
     *
     * @param ID the value for TLOG_BROWSERNAME.ID
     *
     * @mbggenerated
     */
    public void setID(BigDecimal ID) {
        this.ID = ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TLOG_BROWSERNAME.BROWSERNAME
     *
     * @return the value of TLOG_BROWSERNAME.BROWSERNAME
     *
     * @mbggenerated
     */
    public String getBROWSERNAME() {
        return BROWSERNAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TLOG_BROWSERNAME.BROWSERNAME
     *
     * @param BROWSERNAME the value for TLOG_BROWSERNAME.BROWSERNAME
     *
     * @mbggenerated
     */
    public void setBROWSERNAME(String BROWSERNAME) {
        this.BROWSERNAME = BROWSERNAME == null ? null : BROWSERNAME.trim();
    }
}