package com.bizwink.po;

import java.math.BigDecimal;

public class LogBadname {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TLOG_BADNAME.ID
     *
     * @mbggenerated
     */
    private BigDecimal ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TLOG_BADNAME.CODE
     *
     * @mbggenerated
     */
    private String CODE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TLOG_BADNAME.ERR_ENAME
     *
     * @mbggenerated
     */
    private String ERR_ENAME;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TLOG_BADNAME.ERR_CHNAME
     *
     * @mbggenerated
     */
    private String ERR_CHNAME;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TLOG_BADNAME.ID
     *
     * @return the value of TLOG_BADNAME.ID
     *
     * @mbggenerated
     */
    public BigDecimal getID() {
        return ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TLOG_BADNAME.ID
     *
     * @param ID the value for TLOG_BADNAME.ID
     *
     * @mbggenerated
     */
    public void setID(BigDecimal ID) {
        this.ID = ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TLOG_BADNAME.CODE
     *
     * @return the value of TLOG_BADNAME.CODE
     *
     * @mbggenerated
     */
    public String getCODE() {
        return CODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TLOG_BADNAME.CODE
     *
     * @param CODE the value for TLOG_BADNAME.CODE
     *
     * @mbggenerated
     */
    public void setCODE(String CODE) {
        this.CODE = CODE == null ? null : CODE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TLOG_BADNAME.ERR_ENAME
     *
     * @return the value of TLOG_BADNAME.ERR_ENAME
     *
     * @mbggenerated
     */
    public String getERR_ENAME() {
        return ERR_ENAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TLOG_BADNAME.ERR_ENAME
     *
     * @param ERR_ENAME the value for TLOG_BADNAME.ERR_ENAME
     *
     * @mbggenerated
     */
    public void setERR_ENAME(String ERR_ENAME) {
        this.ERR_ENAME = ERR_ENAME == null ? null : ERR_ENAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TLOG_BADNAME.ERR_CHNAME
     *
     * @return the value of TLOG_BADNAME.ERR_CHNAME
     *
     * @mbggenerated
     */
    public String getERR_CHNAME() {
        return ERR_CHNAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TLOG_BADNAME.ERR_CHNAME
     *
     * @param ERR_CHNAME the value for TLOG_BADNAME.ERR_CHNAME
     *
     * @mbggenerated
     */
    public void setERR_CHNAME(String ERR_CHNAME) {
        this.ERR_CHNAME = ERR_CHNAME == null ? null : ERR_CHNAME.trim();
    }
}