package com.bizwink.po;

import java.math.BigDecimal;
import java.util.Date;

public class LogOS {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TLOG_OS.ID
     *
     * @mbggenerated
     */
    private BigDecimal ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TLOG_OS.DOMAINID
     *
     * @mbggenerated
     */
    private BigDecimal DOMAINID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TLOG_OS.HOSTID
     *
     * @mbggenerated
     */
    private BigDecimal HOSTID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TLOG_OS.OSNAME
     *
     * @mbggenerated
     */
    private String OSNAME;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TLOG_OS.COUNTER
     *
     * @mbggenerated
     */
    private BigDecimal COUNTER;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TLOG_OS.LOGDATE
     *
     * @mbggenerated
     */
    private Date LOGDATE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TLOG_OS.ID
     *
     * @return the value of TLOG_OS.ID
     *
     * @mbggenerated
     */
    public BigDecimal getID() {
        return ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TLOG_OS.ID
     *
     * @param ID the value for TLOG_OS.ID
     *
     * @mbggenerated
     */
    public void setID(BigDecimal ID) {
        this.ID = ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TLOG_OS.DOMAINID
     *
     * @return the value of TLOG_OS.DOMAINID
     *
     * @mbggenerated
     */
    public BigDecimal getDOMAINID() {
        return DOMAINID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TLOG_OS.DOMAINID
     *
     * @param DOMAINID the value for TLOG_OS.DOMAINID
     *
     * @mbggenerated
     */
    public void setDOMAINID(BigDecimal DOMAINID) {
        this.DOMAINID = DOMAINID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TLOG_OS.HOSTID
     *
     * @return the value of TLOG_OS.HOSTID
     *
     * @mbggenerated
     */
    public BigDecimal getHOSTID() {
        return HOSTID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TLOG_OS.HOSTID
     *
     * @param HOSTID the value for TLOG_OS.HOSTID
     *
     * @mbggenerated
     */
    public void setHOSTID(BigDecimal HOSTID) {
        this.HOSTID = HOSTID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TLOG_OS.OSNAME
     *
     * @return the value of TLOG_OS.OSNAME
     *
     * @mbggenerated
     */
    public String getOSNAME() {
        return OSNAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TLOG_OS.OSNAME
     *
     * @param OSNAME the value for TLOG_OS.OSNAME
     *
     * @mbggenerated
     */
    public void setOSNAME(String OSNAME) {
        this.OSNAME = OSNAME == null ? null : OSNAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TLOG_OS.COUNTER
     *
     * @return the value of TLOG_OS.COUNTER
     *
     * @mbggenerated
     */
    public BigDecimal getCOUNTER() {
        return COUNTER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TLOG_OS.COUNTER
     *
     * @param COUNTER the value for TLOG_OS.COUNTER
     *
     * @mbggenerated
     */
    public void setCOUNTER(BigDecimal COUNTER) {
        this.COUNTER = COUNTER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TLOG_OS.LOGDATE
     *
     * @return the value of TLOG_OS.LOGDATE
     *
     * @mbggenerated
     */
    public Date getLOGDATE() {
        return LOGDATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TLOG_OS.LOGDATE
     *
     * @param LOGDATE the value for TLOG_OS.LOGDATE
     *
     * @mbggenerated
     */
    public void setLOGDATE(Date LOGDATE) {
        this.LOGDATE = LOGDATE;
    }
}