/*
 * JSP generated by Resin-4.0.58 (built Fri, 24 Aug 2018 01:23:14 PDT)
 */

package _jsp;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.sql.*;
import com.bizwink.cms.security.*;
import com.bizwink.cms.util.*;

public class _headernew__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  private boolean _caucho_isNotModified;
  private com.caucho.jsp.PageManager _jsp_pageManager;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    com.caucho.jsp.PageContextImpl pageContext = _jsp_pageManager.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);

    TagState _jsp_state = null;

    try {
      _jspService(request, response, pageContext, _jsp_application, session, _jsp_state);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_pageManager.freePageContext(pageContext);
    }
  }
  
  private void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response,
              com.caucho.jsp.PageContextImpl pageContext,
              javax.servlet.ServletContext application,
              javax.servlet.http.HttpSession session,
              TagState _jsp_state)
    throws Throwable
  {
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.jsp.tagext.JspTag _jsp_parent_tag = null;
    com.caucho.jsp.PageContextImpl _jsp_parentContext = pageContext;
    response.setContentType("text/html;charset=gbk");

    out.write(_jsp_string0, 0, _jsp_string0.length);
    
    Auth authToken = SessionUtil.getUserAuthorization(request, response, session);
    if (authToken == null) {
        response.sendRedirect(response.encodeRedirectURL("/webbuilder/index.jsp?msg=\u7cfb\u7edf\u8d85\u65f6\uff0c\u8bf7\u91cd\u65b0\u767b\u9646!"));
        return;
    }
    String userid = authToken.getUserID();
    if (userid.compareToIgnoreCase("admin") != 0) {
        if (((authToken != null) && SecurityCheck.hasPermission(authToken, 1)) || SecurityCheck.hasPermission(authToken, 54)) {
            out.println("<td><a href=../column/indexnew.jsp?rightid=1 target=_self><img src='../images/lmsz.gif' border='0'></a></td>");
            //out.println("<td><a href='#' onclick='javascript:columnmgr(" + rightid + ");'><img src='../images/lmsz.gif' border='0'></a></td>");
        }

        if (((authToken != null) && SecurityCheck.hasPermission(authToken, 2)) || SecurityCheck.hasPermission(authToken, 54)) {
            out.println("<td><a href=../template/indexnew.jsp?rightid=2 target=_self><img src='../images/mjgl.gif' border='0'></a></td>");
        }

        //if (((authToken != null) && SecurityCheck.hasPermission(authToken, 2)) || SecurityCheck.hasPermission(authToken, 54)) {
        //    out.println("<td><a href=newtemplate/index.jsp?rightid=2 target=main><img src='images/mjgl.gif' border='0'></a></td>");
        //} else {
        //    out.println("<td><img src='images/mjgl1.gif' border='0'></td>");
        //}

        if (((authToken != null) && SecurityCheck.hasPermission(authToken, 3)) || SecurityCheck.hasPermission(authToken, 54)) {
            out.println("<td><a href=../article/indexnew.jsp?rightid=3 target=_self><img src='../images/wzbj.gif' border='0'></a></td>");
        }

        if (((authToken != null) && SecurityCheck.hasPermission(authToken, 7)) || SecurityCheck.hasPermission(authToken, 54)) {
            out.println("<td><a href=../articlemove/indexnew.jsp?rightid=7 target=_self><img src='../images/ydwz.gif' border='0'></a></td>");
        }

        if (((authToken != null) && SecurityCheck.hasPermission(authToken, 5)) || SecurityCheck.hasPermission(authToken, 54)) {
            out.println("<td><a href=../audit/indexnew.jsp?rightid=5 target=_self><img src='../images/wzsh.gif' border='0'></a></td>");
        }

        if (((authToken != null) && SecurityCheck.hasPermission(authToken, 6)) || SecurityCheck.hasPermission(authToken, 54) || SecurityCheck.hasPermission(authToken, 8)) {
            if (SecurityCheck.hasPermission(authToken, 6) || SecurityCheck.hasPermission(authToken, 54))
                out.println("<td><a href=../publish/indexnew.jsp?rightid=6 target=_self><img src='../images/wzfb.gif' border='0'></a></td>");
            else
                out.println("<td><a href=../publish/indexnew.jsp?rightid=8 target=_self><img src='../images/wzfb.gif' border='0'></a></td>");
        }

        if ((authToken != null) && !SecurityCheck.hasPermission(authToken, 54)) {
            out.println("<td><a href=member/changePass.jsp target=main><img src='../images/xgma.gif' border='0'></a></td>");
        }

        if ((authToken != null) && SecurityCheck.hasPermission(authToken, 54)) {
            out.println("<td><a href=member/index.jsp target=main><img src='../images/xtsz.gif' border='0'></a></td>");
        }

        //if ((authToken != null) && SecurityCheck.hasPermission(authToken, 54)) {
        //    out.println("<td><a href=toolkit/business/index1.jsp target=_parent><img src='../images/dzsw.jpg' border='0'></a></td>");
        //}

        if (authToken != null && SecurityCheck.hasPermission(authToken, 54)) {
            out.println("<td><a href=toolkit/index.jsp target=main><img src='../images/gjx.gif' border='0'></a></td>");
        }
    } else {
        out.println("<td><a href=member/admin_index.jsp target=main><img src='../images/yhgl.gif' border='0'></a></td>");
        out.println("<td><a href=member/siteManage.jsp target=main><img src='../images/zdgl.gif' border='0'></a></td>");
        out.println("<td><a href=adminx/autoPub.jsp target=main><img src='../images/swgl.gif' border='0'></a></td>");
        out.println("<td><a href=program/pmanager.jsp target=main><img src='../images/join2009572.jpg' border='0'></a></td>");
        out.println("<td><a href=member/listStyle.jsp target=main><img src='../images/yswj.gif' border='0'></a></td>");
        out.println("<td><a href=movecolumn/index.jsp target=main><img src='../images/lmqy.gif' border='0'></a></td>");
        out.println("<td><a href=member/logManage.jsp target=main><img src='../images/gzl.gif' border='0'></a></td>");
        //out.println("<td><a href=joincompany/list.jsp target=main>\u52a0\u76df\u5546\u7ba1\u7406</a></td>");
        //out.println("<td><a href=navigator/listNavigator.jsp target=main>\u5bfc\u822a\u6761\u7ba1\u7406</a></td>");
    }

    out.write(_jsp_string0, 0, _jsp_string0.length);
  }

  private com.caucho.make.DependencyContainer _caucho_depends
    = new com.caucho.make.DependencyContainer();

  public java.util.ArrayList<com.caucho.vfs.Dependency> _caucho_getDependList()
  {
    return _caucho_depends.getDependencies();
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    _caucho_depends.add(depend);
  }

  protected void _caucho_setNeverModified(boolean isNotModified)
  {
    _caucho_isNotModified = true;
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;

    if (_caucho_isNotModified)
      return false;

    if (com.caucho.server.util.CauchoSystem.getVersionId() != 6165118203484593848L)
      return true;

    return _caucho_depends.isModified();
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
    TagState tagState;
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("headernew.jsp"), 7390869548860219209L, false);
    _caucho_depends.add(depend);
    loader.addDependency(depend);
  }

  final static class TagState {

    void release()
    {
    }
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void caucho_init(ServletConfig config)
  {
    try {
      com.caucho.server.webapp.WebApp webApp
        = (com.caucho.server.webapp.WebApp) config.getServletContext();
      init(config);
      if (com.caucho.jsp.JspManager.getCheckInterval() >= 0)
        _caucho_depends.setCheckInterval(com.caucho.jsp.JspManager.getCheckInterval());
      _jsp_pageManager = webApp.getJspApplicationContext().getPageManager();
      com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
      com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.InitPageContextImpl(webApp, this);
    } catch (Exception e) {
      throw com.caucho.config.ConfigException.create(e);
    }
  }

  private final static char []_jsp_string0;
  static {
    _jsp_string0 = "\r\n".toCharArray();
  }
}
