package com.bizwink.po;

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * Created by petersong on 16-5-26.
 */
public class ColumnPID implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_COLUMN.ID
     *
     * @mbggenerated
     */
    private BigDecimal ID;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TBL_COLUMN.PARENTID
     *
     * @mbggenerated
     */
    private BigDecimal PARENTID;

    public BigDecimal getID() {
        return ID;
    }

    public void setID(BigDecimal ID) {
        this.ID = ID;
    }

    public BigDecimal getPARENTID() {
        return PARENTID;
    }

    public void setPARENTID(BigDecimal PARENTID) {
        this.PARENTID = PARENTID;
    }
}
