/*
 * JSP generated by Resin-4.0.58 (built Fri, 24 Aug 2018 01:23:14 PDT)
 */

package _jsp._member;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.util.*;
import com.bizwink.cms.util.*;
import com.bizwink.cms.sitesetting.*;
import com.bizwink.cms.security.*;

public class _removesite__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  private boolean _caucho_isNotModified;
  private com.caucho.jsp.PageManager _jsp_pageManager;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    com.caucho.jsp.PageContextImpl pageContext = _jsp_pageManager.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);

    TagState _jsp_state = null;

    try {
      _jspService(request, response, pageContext, _jsp_application, session, _jsp_state);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_pageManager.freePageContext(pageContext);
    }
  }
  
  private void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response,
              com.caucho.jsp.PageContextImpl pageContext,
              javax.servlet.ServletContext application,
              javax.servlet.http.HttpSession session,
              TagState _jsp_state)
    throws Throwable
  {
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.jsp.tagext.JspTag _jsp_parent_tag = null;
    com.caucho.jsp.PageContextImpl _jsp_parentContext = pageContext;
    response.setContentType("text/html;charset=GBK");

    out.write(_jsp_string0, 0, _jsp_string0.length);
    
    Auth authToken = SessionUtil.getUserAuthorization(request, response, session);
    if (authToken.getUserID().compareToIgnoreCase("admin") != 0) {
        request.setAttribute("message", "\u65e0\u7cfb\u7edf\u7ba1\u7406\u5458\u7684\u6743\u9650");
        response.sendRedirect("../index.jsp");
        return;
    }

    int siteid = ParamUtil.getIntParameter(request, "siteid", -1);
    String dname = ParamUtil.getParameter(request, "dname");
    boolean doDelete = ParamUtil.getBooleanParameter(request, "doDelete");
    int currentpage = ParamUtil.getIntParameter(request, "pageno", 0);
    int range = ParamUtil.getIntParameter(request, "range", 0);
    int doSearchFlag = ParamUtil.getIntParameter(request, "searchflag", 0);
    int errcode = 0;

    System.out.println("siteid==" + siteid);

    if (doDelete) {
        ISiteInfoManager siteMgr = SiteInfoPeer.getInstance();
        try {
            errcode = siteMgr.remove(siteid);
        } catch (SiteInfoException ue) {
            errcode = -1;
        }
    }

    out.write(_jsp_string1, 0, _jsp_string1.length);
    out.print((errcode));
    out.write(_jsp_string2, 0, _jsp_string2.length);
    out.print((range));
    out.write(',');
    out.print((currentpage));
    out.write(',');
    out.print((doSearchFlag));
    out.write(_jsp_string3, 0, _jsp_string3.length);
    
    //\u7ad9\u70b9\u5217\u8868
    String[][] titlebars = {
            {"", "siteManage.jsp"},
            {"\u5220\u9664\u7ad9\u70b9", ""}
    };
    String[][] operations = null;

    out.write(_jsp_string4, 0, _jsp_string4.length);
    
if( titlebars != null ) {
    out.println("<table class=line width=100% border=0 cellspacing=0 cellpadding=0>");
    out.println("<tr bgcolor=#003366><td height=2 colspan=2></td></tr>");
    out.println("<tr><td width=50% class=line>");
    int i=0;
    while( titlebars.length > 1 && i < (titlebars.length-1) ) {
	     out.println("<a href=\"javascript:parent.document.location='index.jsp'\" target=_blank>");
	     out.println(titlebars[i][0] +"</a>&gt;");
	     i++;
    }
    if( titlebars.length >= 1 ) {
        out.println(titlebars[i][0]);
    }
    out.println("</td><td width=50% align=right class=line>");
    if (operations != null) {
        i=0;
        while( operations.length > 0 && i < operations.length ) {
            if(operations[i][1] != "")
                out.println("<a href="+ operations[i][1] +">"+ operations[i][0] +"</a>&nbsp;");
            else
                out.println(operations[i][0]);
	    i++;
        }
    }
    out.println("</td></tr>");
    out.println("<tr bgcolor=#003366><td colspan=2 height=2></td>");
    out.println("</tr></table>");
}

    out.write(_jsp_string5, 0, _jsp_string5.length);
    out.print((dname));
    out.write(_jsp_string6, 0, _jsp_string6.length);
    out.print((siteid));
    out.write(_jsp_string7, 0, _jsp_string7.length);
    out.print((dname));
    out.write(_jsp_string8, 0, _jsp_string8.length);
    out.print((range));
    out.write(_jsp_string9, 0, _jsp_string9.length);
    out.print((currentpage));
    out.write(_jsp_string10, 0, _jsp_string10.length);
    out.print((doSearchFlag));
    out.write(_jsp_string11, 0, _jsp_string11.length);
  }

  private com.caucho.make.DependencyContainer _caucho_depends
    = new com.caucho.make.DependencyContainer();

  public java.util.ArrayList<com.caucho.vfs.Dependency> _caucho_getDependList()
  {
    return _caucho_depends.getDependencies();
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    _caucho_depends.add(depend);
  }

  protected void _caucho_setNeverModified(boolean isNotModified)
  {
    _caucho_isNotModified = true;
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;

    if (_caucho_isNotModified)
      return false;

    if (com.caucho.server.util.CauchoSystem.getVersionId() != 6165118203484593848L)
      return true;

    return _caucho_depends.isModified();
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
    TagState tagState;
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("member/removeSite.jsp"), -7864074398058649728L, false);
    _caucho_depends.add(depend);
    loader.addDependency(depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("inc/titlebar.jsp"), 1416346678249567651L, false);
    _caucho_depends.add(depend);
    loader.addDependency(depend);
  }

  final static class TagState {

    void release()
    {
    }
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void caucho_init(ServletConfig config)
  {
    try {
      com.caucho.server.webapp.WebApp webApp
        = (com.caucho.server.webapp.WebApp) config.getServletContext();
      init(config);
      if (com.caucho.jsp.JspManager.getCheckInterval() >= 0)
        _caucho_depends.setCheckInterval(com.caucho.jsp.JspManager.getCheckInterval());
      _jsp_pageManager = webApp.getJspApplicationContext().getPageManager();
      com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
      com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.InitPageContextImpl(webApp, this);
    } catch (Exception e) {
      throw com.caucho.config.ConfigException.create(e);
    }
  }

  private final static char []_jsp_string5;
  private final static char []_jsp_string6;
  private final static char []_jsp_string8;
  private final static char []_jsp_string7;
  private final static char []_jsp_string1;
  private final static char []_jsp_string3;
  private final static char []_jsp_string4;
  private final static char []_jsp_string2;
  private final static char []_jsp_string10;
  private final static char []_jsp_string9;
  private final static char []_jsp_string11;
  private final static char []_jsp_string0;
  static {
    _jsp_string5 = "\r\n\r\n<p>\r\n    &nbsp;&nbsp;<font color=\"red\" size=\"2\">\u786e\u4fe1\u8981\u5220\u9664\u7ad9\u70b9 <b>".toCharArray();
    _jsp_string6 = "</b> ?\r\n</p>\r\n<p>\r\n    &nbsp;&nbsp;\u8be5\u64cd\u4f5c\u5c06\u5220\u9664\u6240\u6709\u6709\u5173\u7ad9\u70b9\u7684\u4fe1\u606f\u5305\u62ec\u6587\u7ae0\uff0c\u6a21\u677f\uff0c\u7528\u6237\u7b49\u6240\u6709\u4fe1\u606f\uff0c<b>\u8bf7\u614e\u91cd\u8003\u8651!!!</b></font>\r\n</p>\r\n\r\n<form action=\"removeSite.jsp\" name=\"deleteForm\" method=\"post\">\r\n    <input type=\"hidden\" name=\"doDelete\" value=\"true\">\r\n    <input type=\"hidden\" name=\"siteid\" value=\"".toCharArray();
    _jsp_string8 = "\">\r\n    <input type=\"hidden\" name=\"range\" value=\"".toCharArray();
    _jsp_string7 = "\">\r\n    <input type=\"hidden\" name=\"dname\" value=\"".toCharArray();
    _jsp_string1 = "\r\n\r\n<html>\r\n<head>\r\n    <title></title>\r\n    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=gb2312\">\r\n    <link rel=\"stylesheet\" type=\"text/css\" href=\"../style/global.css\">\r\n    <script src=\"../js/jquery-1.12.4.js\" type=\"text/javascript\"></script>\r\n    <script language=\"javascript\">\r\n        $(document).ready(function(){\r\n            var errcode=".toCharArray();
    _jsp_string3 = ");\r\n                window.close();\r\n            } else if (errcode==-1) {\r\n                alert(\"\u7ad9\u70b9\u5220\u9664\u5931\u8d25\uff01\");\r\n                window.close();\r\n            }\r\n        });\r\n    </script>\r\n</head>\r\n<body>\r\n".toCharArray();
    _jsp_string4 = "\r\n".toCharArray();
    _jsp_string2 = ";\r\n            if (errcode === 1) {\r\n                alert(\"\u7ad9\u70b9\u5220\u9664\u6210\u529f\uff01\");\r\n                window.opener.userInfoList(".toCharArray();
    _jsp_string10 = "\">\r\n    <input type=\"hidden\" name=\"searchflag\" value=\"".toCharArray();
    _jsp_string9 = "\">\r\n    <input type=\"hidden\" name=\"pageno\" value=\"".toCharArray();
    _jsp_string11 = "\">\r\n    &nbsp;&nbsp;\r\n    <input type=\"submit\" value=\" \u786e\u5b9a \">\r\n    &nbsp;&nbsp;&nbsp;\r\n    <input type=\"button\" name=\"cancel\" value=\" \u53d6\u6d88 \" style=\"font-weight:bold;\" onclick=\"javascript:window.close();\">\r\n</form>\r\n</body>\r\n</html>\r\n".toCharArray();
    _jsp_string0 = "\r\n\r\n".toCharArray();
  }
}
